'use client';
import {editorialImages,imageMarkdown} from '../../lib/insights/editorial-images';
import {useCallback,useEffect,useRef,useState} from 'react';
import {EditorialMarkdown} from '../insights/editorial-markdown';
import {dubaiCreekDraft} from '../../content/editorial-drafts/dubai-creek';
import styles from './editorial-workspace.module.css';
type Source={id:string;kind:string;publisher:string;title:string;href:string;checkedAt:string};
type Article={slug:string;title:string;summary:string;bodyMarkdown:string;locale:string;marketKey:string;contentType:string;evidenceState:string;reviewedBy:string;sources:Source[]};
type Item={id:string|null;slug:string;version:number;state:string;scheduled_at:string|null;error_code:string|null;payload:Partial<Article>};
const endpoint='/api/internal/editorial-operations/';
const labels:Record<string,string>={draft:'초안',scheduled:'예약됨',publishing:'발행 중',refreshing:'공개 반영 중',published:'발행됨',failed:'발행 실패',cancelled:'예약 취소',review:'검토 중',archived:'보관됨'};
const empty=():Article=>({slug:'',title:'',summary:'',bodyMarkdown:'',locale:'en',marketKey:'global',contentType:'data-story',evidenceState:'partial',reviewedBy:'',sources:[]});
const errorText:Record<string,string>={unauthorized:'로그인이 만료되었습니다. 관리자 화면을 새로 열어 로그인하세요.',version_conflict:'다른 변경이 있습니다. 입력한 내용을 복사해 둔 뒤 목록에서 다시 열어주세요.',reserved_portfolio_slug:'기존 고정 가이드의 주소입니다. 새 글은 다른 주소를 사용하세요.',database_not_configured:'글 저장소가 연결되지 않았습니다.',invalid_article:'주소·제목·요약·본문을 확인하세요. 발행에는 검토자와 1차 출처가 필요합니다.',storage_unavailable:'글 저장소에 연결하지 못했습니다.'};
async function api(url:string,body?:unknown){const r=await fetch(url,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const v=await r.json();if(!r.ok)throw new Error(errorText[v.error]??'요청을 처리하지 못했습니다. 입력값과 연결을 확인하세요.');return v;}
export function EditorialOperationsPanel(){
 const [items,setItems]=useState<Item[]>([]),[article,setArticle]=useState<Article>(empty),[selected,setSelected]=useState<Item|null>(null),[version,setVersion]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[loaded,setLoaded]=useState(false),[dirty,setDirty]=useState(false),[preview,setPreview]=useState(false),[query,setQuery]=useState(''),[stateFilter,setStateFilter]=useState(''),[scheduled,setScheduled]=useState('');
 const lock=useRef(false);
 const [uploading,setUploading]=useState(false);
 const photos=editorialImages(article.bodyMarkdown);
 const notice=useRef<HTMLParagraphElement>(null);
 useEffect(()=>{if(message)notice.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[message]);
 const load=useCallback(async()=>{const data=await api(endpoint);setItems(data.items);setLoaded(true);},[]);
 useEffect(()=>{
  let active=true;
  void api(endpoint).then(data=>{if(active){setItems(data.items);setLoaded(true);}}).catch(e=>{if(active)setMessage(e.message);});
  return ()=>{active=false;};
 },[]);
 useEffect(()=>{if(!dirty)return;const protect=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',protect);return()=>window.removeEventListener('beforeunload',protect);},[dirty]);
 const canLeave=()=>!dirty||window.confirm('저장하지 않은 변경이 있습니다. 버리고 다른 글을 열까요?');
 function change<K extends keyof Article>(key:K,value:Article[K]){setArticle(a=>({...a,[key]:value}));setDirty(true);setMessage('');}
 function newArticle(template?:Article){if(busy||uploading||!canLeave())return;setSelected(null);setVersion(0);setArticle(template?structuredClone(template):empty());setDirty(Boolean(template));setPreview(false);setMessage('');setScheduled('');}
 async function open(item:Item){if(busy||uploading||!canLeave())return;setBusy(true);try{const data=await api(`${endpoint}?${item.id?'id='+encodeURIComponent(item.id):'slug='+encodeURIComponent(item.slug)}`);const next=data.item as Item;setSelected(next);setVersion(next.version);setArticle({...empty(),...next.payload,marketKey:next.payload.marketKey??'global',reviewedBy:next.payload.reviewedBy??'',sources:next.payload.sources??[]});setDirty(false);setPreview(false);setScheduled('');setMessage('');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function save(action:'draft'|'schedule'|'publish'){
  if(lock.current||uploading)return;
  if(action!=='draft'&&article.reviewedBy.trim().length<2){setMessage('검토자 이름을 2자 이상 입력하세요. 본문 아래 검토자 칸에 입력한 뒤 발행할 수 있습니다.');return;}
  if(action!=='draft'&&!window.confirm(action==='publish'?'이 내용으로 사이트에 지금 발행할까요?':'선택한 시각에 이 내용으로 발행하도록 예약할까요?'))return;
  if(action==='schedule'&&(!scheduled||!Number.isFinite(new Date(scheduled).getTime()))){setMessage('발행 시각을 입력하세요.');return;}
  lock.current=true;setBusy(true);setMessage('');
  try{const result=await api(endpoint,{action,article,version,scheduledAt:scheduled?new Date(scheduled).toISOString():null});setVersion(result.version);setSelected({id:result.id,slug:article.slug,version:result.version,state:result.state,scheduled_at:null,error_code:null,payload:article});setDirty(false);await load();const done=result.results?.some((r:{state:string})=>r.state==='published');setMessage(action==='publish'?(done?'사이트에 발행했습니다.':'저장됐지만 발행 완료는 확인되지 않았습니다. 목록에서 상태를 확인하세요.'):action==='draft'?'초안을 저장했습니다. 공개된 글은 바뀌지 않습니다.':'발행을 예약했습니다. 예약 시각 이후 정기 처리로 공개됩니다.');}catch(e){setMessage((e as Error).message);}finally{lock.current=false;setBusy(false);}
 }
 async function cancel(item:Item){if(busy||!window.confirm('이 글의 발행 예약을 취소할까요? 원고는 유지됩니다.'))return;setBusy(true);try{await api(endpoint,{action:'cancel',id:item.id,version:item.version});await load();if(selected?.id===item.id){setVersion(item.version+1);setSelected({...item,state:'cancelled',version:item.version+1});}setMessage('예약을 취소했습니다.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function upload(file:File,cover:boolean,replacing?:string){
  if(busy||uploading)return;setUploading(true);setMessage('');
  try{
   if(file.size>25*1024*1024)throw new Error('사진은 25MB 이하로 선택하세요.');
   const bitmap=await createImageBitmap(file);const scale=Math.min(1,1800/Math.max(bitmap.width,bitmap.height));
   const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));
   const context=canvas.getContext('2d');if(!context){bitmap.close();throw new Error('사진을 처리할 수 없습니다.');}context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
   const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',0.82));if(!blob||blob.size>1572864)throw new Error('사진을 더 작게 저장한 뒤 다시 선택하세요.');
   const r=await fetch('/api/internal/editorial-images/',{method:'POST',headers:{'Content-Type':'image/jpeg'},body:blob});const data=await r.json();if(!r.ok)throw new Error(r.status===401?'로그인 시간이 만료됐습니다. 다시 로그인하세요.':'사진을 저장하지 못했습니다. 잠시 뒤 다시 시도하세요.');
   const previous=replacing?photos.find(photo=>photo.line===replacing):undefined;
   const line=imageMarkdown({src:data.src,alt:previous?.alt??file.name.replace(/\.[^.]+$/,''),caption:previous?.caption??''});
   change('bodyMarkdown',replacing?article.bodyMarkdown.replace(replacing,line):cover?line+'\n\n'+article.bodyMarkdown:article.bodyMarkdown+'\n\n'+line);
   setMessage('사진을 첨부했습니다. 설명·출처를 확인하고 초안을 저장하거나 발행하세요.');
  }catch(e){setMessage((e as Error).message||'이 사진 형식을 읽을 수 없습니다. JPG 또는 PNG로 선택하세요.');}finally{setUploading(false);}
 }
 const filtered=items.filter(i=>(!stateFilter||i.state===stateFilter)&&`${i.payload.title} ${i.slug}`.toLowerCase().includes(query.toLowerCase()));
 const href=`${article.locale==='en'?'':article.locale==='ko'?'/ko':'/zh-cn'}/news/${article.slug}/`;
 const changeSource=(index:number,key:keyof Source,value:string)=>change('sources',article.sources.map((s,i)=>i===index?{...s,[key]:value}:s));
 return <section className={styles.workspace} aria-label="글 편집실">
  <div className={styles.toolbar}><button disabled={busy||uploading} onClick={()=>newArticle()}>새 글</button><button disabled={busy||uploading} onClick={()=>newArticle(dubaiCreekDraft)}>두바이 도시탐방 초안 열기</button><button disabled={busy||uploading} onClick={()=>void load().catch(e=>setMessage(e.message))}>목록 새로고침</button></div>
  {message&&<p ref={notice} role="alert" className={styles.message}>{message}</p>}
  <div className={styles.layout}><aside className={styles.list} aria-label="글 목록"><label>글 검색<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="제목 또는 주소" /></label><label>상태<select value={stateFilter} onChange={e=>setStateFilter(e.target.value)}><option value="">전체</option>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><p>최근 저장 글 100건</p>
  {!loaded?<p>목록을 불러오는 중입니다. 연결 실패 시 새로고침하세요.</p>:!filtered.length?<p>조건에 맞는 글이 없습니다. 새 글이나 두바이 초안으로 시작하세요.</p>:<ul>{filtered.map(i=><li key={i.slug}><button disabled={busy||uploading||['publishing','refreshing'].includes(i.state)} aria-current={selected?.slug===i.slug?'true':undefined} onClick={()=>void open(i)}><strong>{String(i.payload.title||i.slug)}</strong><span>{labels[i.state]??i.state} · {i.payload.locale??'en'} · {i.payload.marketKey??'global'}</span>{i.scheduled_at&&<small>{new Date(i.scheduled_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} KST</small>}{i.error_code&&<small>발행을 완료하지 못했습니다. 열어서 확인하세요.</small>}</button>{i.id&&['scheduled','failed'].includes(i.state)&&<button disabled={busy||uploading} onClick={()=>void cancel(i)}>예약 취소</button>}</li>)}</ul>}
  <details><summary>기존 고정 콘텐츠</summary><p>기존 지역 가이드·체크리스트·용어집은 아직 코드로 관리됩니다. 이 편집실에서는 저장소에 등록한 기사와 신규 도시탐방 글을 관리합니다.</p><a href="/guides/" target="_blank" rel="noreferrer">가이드 목록 보기</a></details></aside>
  <div className={styles.editor}><div className={styles.toolbar}><h2>{selected?'글 수정':'새 글 작성'}</h2><span>{dirty?'저장 전 변경 있음':selected?'저장된 내용':'새 초안'}</span><button disabled={busy||uploading} onClick={()=>setPreview(!preview)}>{preview?'편집하기':'미리보기'}</button></div>
  {preview?<article className={styles.preview} lang={article.locale}><h1>{article.title||'제목 없음'}</h1><p>{article.summary}</p><EditorialMarkdown source={article.bodyMarkdown}/>{article.sources.length>0&&<section><h2>출처</h2><ul>{article.sources.map(s=><li key={s.id}>{/^https:\/\//.test(s.href)?<a href={s.href} target="_blank" rel="noreferrer">{s.publisher} · {s.title}</a>:s.title}</li>)}</ul></section>}</article>:<div className={styles.fields}>
  <label>제목<input disabled={busy||uploading} value={article.title} maxLength={180} onChange={e=>change('title',e.target.value)}/></label><div className={styles.row}><label>주소 이름<input disabled={busy||uploading||Boolean(selected)} value={article.slug} onChange={e=>change('slug',e.target.value)} placeholder="dubai-neighbourhood-walk"/></label><label>언어<select disabled={busy||uploading||Boolean(selected)} value={article.locale} onChange={e=>change('locale',e.target.value)}><option value="en">English</option><option value="ko">한국어</option><option value="zh-CN">简体中文</option></select></label><label>도시<select disabled={busy||uploading} value={article.marketKey} onChange={e=>change('marketKey',e.target.value)}>{[['global','전체'],['seoul','서울'],['tokyo','도쿄'],['singapore','싱가포르'],['dubai','두바이']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label></div>
  <label>요약<textarea disabled={busy||uploading} rows={3} value={article.summary} maxLength={600} onChange={e=>change('summary',e.target.value)}/></label><fieldset disabled={busy||uploading} className={styles.photos}><legend>사진 첨부</legend><p>첫 번째 사진이 대표 사진입니다. JPG·PNG·WebP를 선택하면 웹용으로 줄여 저장합니다.</p><div className={styles.row}><label>대표 사진 추가<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.currentTarget.files?.[0];if(f)void upload(f,true);e.currentTarget.value='';}}/></label><label>본문 끝에 사진 추가<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.currentTarget.files?.[0];if(f)void upload(f,false);e.currentTarget.value='';}}/></label></div>{uploading&&<p role="status">사진을 저장하고 있습니다…</p>}{photos.map((photo,index)=><div className={styles.photoRow} key={photo.src+index}><img src={photo.src} alt={photo.alt}/><div><strong>{index===0?'대표 사진':`본문 사진 ${index}`}</strong><label>사진 설명<input value={photo.alt} onChange={e=>change('bodyMarkdown',article.bodyMarkdown.replace(photo.line,imageMarkdown({...photo,alt:e.target.value})))}/></label><label>캡션·촬영자·출처·이용조건<input value={photo.caption} onChange={e=>change('bodyMarkdown',article.bodyMarkdown.replace(photo.line,imageMarkdown({...photo,caption:e.target.value})))}/></label><label>이 사진 교체<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.currentTarget.files?.[0];if(f)void upload(f,index===0,photo.line);e.currentTarget.value='';}}/></label><button type="button" onClick={()=>change('bodyMarkdown',article.bodyMarkdown.replace(photo.line,''))}>글에서 사진 삭제</button>{index>0&&<button type="button" onClick={()=>change('bodyMarkdown',photo.line+'\n\n'+article.bodyMarkdown.replace(photo.line,''))}>대표 사진으로</button>}</div></div>)}</fieldset>
  <label>본문<textarea disabled={busy||uploading} className={styles.body} rows={18} value={article.bodyMarkdown} onChange={e=>change('bodyMarkdown',e.target.value)}/></label><p>소제목은 ##, 목록은 - 로 시작하세요. 오른쪽 위 ‘미리보기’에서 실제 문단 구성을 확인할 수 있습니다.</p>
  <div className={styles.row}><label>검토자<input disabled={busy||uploading} value={article.reviewedBy} onChange={e=>change('reviewedBy',e.target.value)}/></label><label>근거 확인<select disabled={busy||uploading} value={article.evidenceState} onChange={e=>change('evidenceState',e.target.value)}><option value="partial">일부 확인 · 남은 확인 필요</option><option value="verified">검토 완료</option><option value="not-applicable">근거 검증 대상 아님</option></select></label></div>
  <fieldset disabled={busy||uploading}><legend>출처</legend>{article.sources.map((s,i)=><div className={styles.source} key={s.id}><div className={styles.row}><label>발행기관<input value={s.publisher} onChange={e=>changeSource(i,'publisher',e.target.value)}/></label><label>자료 제목<input value={s.title} onChange={e=>changeSource(i,'title',e.target.value)}/></label></div><label>원문 주소<input type="url" value={s.href} onChange={e=>changeSource(i,'href',e.target.value)}/></label><div className={styles.row}><label>확인일<input type="date" value={s.checkedAt.slice(0,10)} onChange={e=>changeSource(i,'checkedAt',e.target.value)}/></label><label>구분<select value={s.kind} onChange={e=>changeSource(i,'kind',e.target.value)}><option value="primary">1차 출처</option><option value="secondary">보조 출처</option></select></label><button onClick={()=>change('sources',article.sources.filter((_,j)=>i!==j))}>출처 삭제</button></div></div>)}<button onClick={()=>change('sources',[...article.sources,{id:crypto.randomUUID(),kind:'primary',publisher:'',title:'',href:'',checkedAt:new Date().toISOString().slice(0,10)}])}>출처 추가</button></fieldset></div>}
  <div className={styles.actions}><button disabled={busy||uploading} onClick={()=>void save('draft')}>{busy?'처리 중…':'초안 저장'}</button><button disabled={busy||uploading} onClick={()=>void save('publish')}>지금 발행</button><label>예약 시각 · 기기 시간대<input disabled={busy||uploading} type="datetime-local" value={scheduled} onChange={e=>setScheduled(e.target.value)}/></label><button disabled={busy||uploading||!scheduled} onClick={()=>void save('schedule')}>예약 발행</button></div><p>발행 전 검토자와 출처를 확인하세요. 수정 초안을 저장해도 기존 공개 글은 유지됩니다.</p>{selected&&article.slug&&<a href={href} target="_blank" rel="noreferrer">공개 주소 확인 (미발행 글은 열리지 않습니다)</a>}
  </div></div><details><summary>배포·운영 도구</summary><a href="https://github.com/007shp18-dot/koreahomeguide/pulls" target="_blank" rel="noreferrer">사이트 변경 내역</a> · <a href="https://github.com/007shp18-dot/koreahomeguide/deployments" target="_blank" rel="noreferrer">사이트 배포 상태</a></details>
 </section>;
}
