'use client';
import {useEffect,useState} from 'react';
import styles from './workspace.module.css';
type Item={id:string;slug:string;version:number;state:string;scheduled_at:string|null;error_code:string|null;payload:Record<string,unknown>};
const endpoint='/api/internal/editorial-operations/';
export function EditorialOperationsPanel() {
 const [items,setItems]=useState<Item[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 const [version,setVersion]=useState(0);const [slug,setSlug]=useState('');const [title,setTitle]=useState('');const [summary,setSummary]=useState('');const [body,setBody]=useState('');const [locale,setLocale]=useState('en');const [market,setMarket]=useState('global');const [reviewer,setReviewer]=useState('');const [scheduled,setScheduled]=useState('');const [sources,setSources]=useState('[]');
 const load=async()=>{const response=await fetch(endpoint,{cache:'no-store'});if(!response.ok)throw new Error('발행 목록을 불러오지 못했습니다.');setItems((await response.json()).items);};
 useEffect(()=>{void load().catch(()=>setMessage('발행 목록을 불러오지 못했습니다. 새로고침하거나 로그인 상태를 확인하세요.'));},[]);
 async function command(command:Record<string,unknown>) {setBusy(true);setMessage('');try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)});const result=await response.json();if(!response.ok)throw new Error(result.error==='version_conflict'?'다른 변경이 있습니다. 목록에서 다시 열어주세요.':`저장 실패: ${result.error}`);if(result.version)setVersion(result.version);await load();setMessage('처리가 완료되었습니다.');}catch(error){setMessage(error instanceof Error?error.message:'처리 실패');}finally{setBusy(false);}}
 const sourceRows=JSON.parse(sources) as Record<string,string>[];
 function changeSource(index:number,key:string,value:string){setSources(JSON.stringify(sourceRows.map((row,i)=>i===index?{...row,[key]:value}:row)));}
 function save(action:string) {try{const parsed=JSON.parse(sources);if(action==='schedule'&&!scheduled)throw new Error('발행 시각을 입력하세요.');void command({action,version,scheduledAt:scheduled?new Date(scheduled).toISOString():null,article:{slug,title,summary,bodyMarkdown:body,locale,marketKey:market,contentType:'data-story',evidenceState:'verified',reviewedBy:reviewer,sources:parsed}});}catch{setMessage('발행 시각과 출처를 확인하세요.');}}
 async function edit(selected:Item){let item:Item;try{const response=await fetch(`${endpoint}?id=${selected.id}`,{cache:'no-store'});if(!response.ok)throw new Error();item=(await response.json()).item;}catch{setMessage('기사를 불러오지 못했습니다.');return;}const a=item.payload;setVersion(item.version);setSlug(item.slug);setTitle(String(a.title??''));setSummary(String(a.summary??''));setBody(String(a.bodyMarkdown??''));setLocale(String(a.locale??'en'));setMarket(String(a.marketKey??'global'));setReviewer(String(a.reviewedBy??''));setSources(JSON.stringify(a.sources??[],null,2));setScheduled('');}
 return <section aria-label="배포와 기사 발행"><h2>배포·기사 발행</h2><p>코드 변경은 검증 후 개별 병합할 수 있습니다. 병합 상태와 실제 배포 완료 상태를 각각 확인하세요.</p><p><a href="https://github.com/007shp18-dot/koreahomeguide/pulls" target="_blank" rel="noreferrer">변경 PR</a> · <a href="https://github.com/007shp18-dot/koreahomeguide/deployments" target="_blank" rel="noreferrer">배포 상태 확인</a></p><p>데이터 갱신과 실패 기록은 ‘정기 수집 운영’에서 확인합니다. 기사는 예약 시각 이후 15분 주기 점검으로 공개되며 전체 사이트 빌드를 실행하지 않습니다.</p>
 <h3>기사 작성·예약</h3><p>검토한 신규 인사이트를 등록합니다. 발행된 글의 수정과 기존 코드 기사 변경은 현재 별도 편집 절차를 사용합니다.</p>
 <div className={styles.formGrid}>
 <label>주소 이름<input value={slug} onChange={e=>{setSlug(e.target.value);setVersion(0);}} placeholder="neighbourhood-story" /></label>
 <label>언어<select value={locale} onChange={e=>setLocale(e.target.value)}><option value="en">English</option><option value="ko">한국어</option><option value="zh-CN">简体中文</option></select></label>
 <label>시장<select value={market} onChange={e=>setMarket(e.target.value)}><option value="global">전체·기타 도시</option><option value="seoul">서울</option><option value="singapore">싱가포르</option><option value="dubai">두바이</option><option value="tokyo">도쿄</option></select></label>
 <label>제목<input value={title} onChange={e=>setTitle(e.target.value)} /></label><label>요약<textarea value={summary} onChange={e=>setSummary(e.target.value)} /></label>
 <label>본문 Markdown<textarea rows={12} value={body} onChange={e=>setBody(e.target.value)} /></label>
 <label>검토자<input value={reviewer} onChange={e=>setReviewer(e.target.value)} /></label>
 <label>발행 시각 · 현재 기기 시간대<input type="datetime-local" value={scheduled} onChange={e=>setScheduled(e.target.value)} /></label>
 <fieldset><legend>검증 출처</legend>{sourceRows.map((source,index)=><div key={source.id}><label>발행기관<input value={source.publisher??''} onChange={e=>changeSource(index,'publisher',e.target.value)} /></label><label>자료 제목<input value={source.title??''} onChange={e=>changeSource(index,'title',e.target.value)} /></label><label>원문 URL<input type="url" value={source.href??''} onChange={e=>changeSource(index,'href',e.target.value)} /></label><label>확인일<input type="date" value={(source.checkedAt??'').slice(0,10)} onChange={e=>changeSource(index,'checkedAt',e.target.value)} /></label><label>출처 구분<select value={source.kind??'primary'} onChange={e=>changeSource(index,'kind',e.target.value)}><option value="primary">1차 출처</option><option value="secondary">보조 출처</option></select></label><button type="button" onClick={()=>setSources(JSON.stringify(sourceRows.filter((_,i)=>i!==index)))}>출처 삭제</button></div>)}<button type="button" onClick={()=>setSources(JSON.stringify([...sourceRows,{id:`source-${Date.now()}`,kind:'primary',publisher:'',title:'',href:'',checkedAt:new Date().toISOString().slice(0,10)}]))}>출처 추가</button></fieldset>
 </div><p>예약에는 검토자와 최소 한 개의 1차 출처가 필요합니다. 원문 주소는 HTTPS를 사용하세요.</p>
 <button type="button" disabled={busy} onClick={()=>save('draft')}>초안 저장</button>{' '}<button type="button" disabled={busy} onClick={()=>save('schedule')}>검토 완료·예약</button>{' '}<button type="button" disabled={busy} onClick={()=>void command({action:'publish-due'})}>발행 시각 지난 기사 처리</button>
 {message&&<p role="status">{message}</p>}<div className={styles.tableScroll}><table><caption>최근 기사 100건 · 상태와 실패 원인</caption><thead><tr><th>기사</th><th>상태</th><th>예약 UTC</th><th>오류</th><th>작업</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{String(item.payload.title)}</td><td>{item.state}</td><td>{item.scheduled_at??'—'}</td><td>{item.error_code??'—'}</td><td>{!['publishing','refreshing','published'].includes(item.state)&&<button disabled={busy} onClick={()=>void edit(item)}>열기</button>}{['draft','scheduled','failed'].includes(item.state)&&<button disabled={busy} onClick={()=>void command({action:'cancel',id:item.id,version:item.version})}>예약 취소</button>}</td></tr>)}</tbody></table></div></section>;
}
