@echo off
setlocal enabledelayedexpansion
cd /d "%~dp0"
set "OUT=%~dp0git-report.txt"

echo KoreaHomeGuide git diagnostics > "%OUT%"
echo Generated by git-check.bat >> "%OUT%"
echo. >> "%OUT%"

echo.
echo   Running git diagnostics. Read-only - nothing is changed.
echo.

echo [1] FOLDER >> "%OUT%"
cd >> "%OUT%" 2>&1
echo. >> "%OUT%"

echo [2] GIT VERSION >> "%OUT%"
git --version >> "%OUT%" 2>&1
echo. >> "%OUT%"

echo [3] INSIDE A GIT REPO >> "%OUT%"
git rev-parse --is-inside-work-tree >> "%OUT%" 2>&1
echo. >> "%OUT%"

echo [4] REMOTE >> "%OUT%"
git remote -v >> "%OUT%" 2>&1
echo. >> "%OUT%"

echo [5] BRANCHES >> "%OUT%"
git branch -vv >> "%OUT%" 2>&1
echo. >> "%OUT%"

echo [6] LAST 12 COMMITS >> "%OUT%"
git log --oneline -12 >> "%OUT%" 2>&1
echo. >> "%OUT%"

echo [7] STATUS BEFORE FETCH >> "%OUT%"
git status >> "%OUT%" 2>&1
echo. >> "%OUT%"

echo   Contacting the remote, this may take a moment...
echo [8] FETCH >> "%OUT%"
git fetch --all --prune >> "%OUT%" 2>&1
echo. >> "%OUT%"

echo [9] STATUS AFTER FETCH >> "%OUT%"
git status >> "%OUT%" 2>&1
echo. >> "%OUT%"

echo [10] AHEAD BEHIND vs UPSTREAM >> "%OUT%"
git rev-list --left-right --count HEAD...@{u} >> "%OUT%" 2>&1
echo. >> "%OUT%"

echo [11] COMMITS ON REMOTE NOT HERE >> "%OUT%"
git log --oneline HEAD..@{u} >> "%OUT%" 2>&1
echo. >> "%OUT%"

echo [12] STASHES >> "%OUT%"
git stash list >> "%OUT%" 2>&1
echo. >> "%OUT%"

echo [13] CHANGED FILES >> "%OUT%"
git status --porcelain >> "%OUT%" 2>&1
echo. >> "%OUT%"

echo [14] VERCEL LINK >> "%OUT%"
if exist ".vercel\project.json" (type ".vercel\project.json" >> "%OUT%" 2>&1) else (echo no .vercel folder >> "%OUT%")
echo. >> "%OUT%"

echo.
echo   Done. git-report.txt has been created in this folder.
echo   Tell Claude it is finished.
echo.
pause
