const areaSelect = document.querySelector('#exploreArea');
const typeSelect = document.querySelector('#exploreType');
const maxRentSelect = document.querySelector('#exploreMaxRent');
const maxDepositSelect = document.querySelector('#exploreMaxDeposit');
const exploreButton = document.querySelector('#exploreButton');
const currencySelect = document.querySelector('#currencySelect');
const languageSwitch = document.querySelector('#languageSwitch');
const title = document.querySelector('#explorerTitle');
const status = document.querySelector('#explorerStatus');
const dataThrough = document.querySelector('#explorerDataThrough');
const metricRent = document.querySelector('#metricRent');
const metricDeposit = document.querySelector('#metricDeposit');
const metricContracts = document.querySelector('#metricContracts');
const metricChange = document.querySelector('#metricChange');
const dongList = document.querySelector('#dongList');
const buildingList = document.querySelector('#buildingList');
const budgetFilterNote = document.querySelector('#budgetFilterNote');
let fxRates = {};
let currentAreaData = null;
let currentData = null;
let currentDong = '';

const DISTRICT_NAMES = { 'all':'全首尔支持地区', '11680':'江南区', '11440':'麻浦区', '11170':'龙山区', '11200':'城东区', '11560':'永登浦区', '11620':'冠岳区', '11230':'东大门区', '11410':'西大门区', '11290':'城北区', '11215':'广津区' };
const TYPE_NAMES = { apartment:'公寓', officetel:'Officetel', villa:'低层住宅（联排/多户住宅）', detached:'独栋 / 多户住宅' };
const DONG_NAMES_ZH = {
  '연남동':'延南洞 (연남동)', '서교동':'西桥洞 (서교동)', '망원동':'望远洞 (망원동)', '합정동':'合井洞 (합정동)',
  '역삼동':'驿三洞 (역삼동)', '논현동':'论岘洞 (논현동)', '청담동':'清潭洞 (청담동)', '삼성동':'三成洞 (삼성동)',
  '한남동':'汉南洞 (한남동)', '이태원동':'梨泰院洞 (이태원동)', '성수동1가':'圣水洞1街 (성수동1가)', '성수동2가':'圣水洞2街 (성수동2가)',
  '여의도동':'汝矣岛洞 (여의도동)', '당산동':'堂山洞 (당산동)'
};
const LISTING_NOTE = '没有实时房源；这里展示的是历史真实签约数据。';

function selectedCurrency() { return currencySelect ? currencySelect.value : 'KRW'; }
function moneyHtml(amountWon) { if (amountWon == null) return '<span class="money-primary">数据不足</span>'; return KHGCurrency.formatMoneyHtml(amountWon, selectedCurrency(), fxRates, 'zh-CN'); }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[char]); }
function areaName() { return DISTRICT_NAMES[areaSelect.value] || areaSelect.options[areaSelect.selectedIndex].text; }
function typeName(type = typeSelect.value) { return TYPE_NAMES[type] || KHGExplorer.propertyTypeLabel(type); }
function dongDisplayName(dong) { return DONG_NAMES_ZH[dong] || dong; }
function formatArea(area) { return area == null ? '—' : `${Number(area).toFixed(1)}㎡`; }
function budgetValues() { return { maxRent:Number(maxRentSelect && maxRentSelect.value || 0), maxDeposit:Number(maxDepositSelect && maxDepositSelect.value || 0) }; }
function hasBudgetFilter() { const { maxRent,maxDeposit }=budgetValues(); return Boolean(maxRent||maxDeposit); }
function filterDongsByBudget(items) { return KHGExplorer.filterDongsByBudget(items, budgetValues()); }
function updateBudgetNote(filteredCount,totalCount) { if(!budgetFilterNote)return; budgetFilterNote.textContent=hasBudgetFilter()?`${totalCount} 个街区中有 ${filteredCount} 个符合所选月租/押金中位数条件`:'选择街区后查看具体建筑'; }
function currentParams(includeDong=true) { const params=new URLSearchParams({lawdCd:areaSelect.value,type:typeSelect.value}); const {maxRent,maxDeposit}=budgetValues(); if(maxRent)params.set('maxRent',String(maxRent)); if(maxDeposit)params.set('maxDeposit',String(maxDeposit)); if(includeDong&&currentDong)params.set('dong',currentDong); return params; }
function updateLanguageSwitch(){if(languageSwitch)languageSwitch.href=`/explore/?${currentParams(true).toString()}`;}

function representativeBand(item){const bands=Array.isArray(item&&item.depositBands)?item.depositBands:[]; if(!bands.length)return null; const {maxRent,maxDeposit}=budgetValues(); const matches=bands.filter(band=>{const rent=Number(band.medianMonthlyRentWon),deposit=Number(band.medianDepositWon); if(maxRent&&(!Number.isFinite(rent)||rent>maxRent))return false; if(maxDeposit&&(!Number.isFinite(deposit)||deposit>maxDeposit))return false; return true;}); const pool=matches.length?matches:bands; return [...pool].sort((a,b)=>Number(b.count||0)-Number(a.count||0))[0]||null;}

function renderDongs(dongs){if(!dongList)return; const allItems=Array.isArray(dongs)?dongs:[]; const items=filterDongsByBudget(allItems); updateBudgetNote(items.length,allItems.length); if(hasBudgetFilter()&&!items.length){dongList.innerHTML='<div class="explorer-empty">没有街区的月租和押金中位数同时符合当前预算。请提高月租或押金预算后再试。</div>';return;} if(!items.length){dongList.innerHTML='<div class="explorer-empty">当前条件下暂时没有可用的街区摘要。</div>';return;} dongList.innerHTML=items.map(item=>{const band=representativeBand(item); const rentValue=band?band.medianMonthlyRentWon:(item.contextualMedianMonthlyRentWon??item.medianMonthlyRentWon); const depositValue=band?band.medianDepositWon:(item.contextualMedianDepositWon??item.medianDepositWon); const rent=rentValue==null?'—':moneyHtml(rentValue); const deposit=depositValue==null?'—':moneyHtml(depositValue); const itemAreaCode=item.districtCode||areaSelect.value; const districtName=DISTRICT_NAMES[itemAreaCode]||item.districtName||''; const seoHref=KHGExplorer.buildDongSeoUrl({lawdCd:itemAreaCode,type:typeSelect.value,dong:item.dong,lang:'zh'}); return `<a class="neighborhood-card" href="${escapeHtml(seoHref)}"><span class="neighborhood-card-main"><strong>${escapeHtml(dongDisplayName(item.dong))}</strong><small>${districtName?`${escapeHtml(districtName)} · `:''}${Number(item.contractCount||0).toLocaleString('zh-CN')} 笔近期成交</small></span><span class="neighborhood-card-metric"><small>参考月租</small><strong>${rent}</strong></span><span class="neighborhood-card-metric"><small>参考押金</small><strong>${deposit}</strong></span><span class="neighborhood-card-cta">查看街区 →</span></a>`;}).join('');}

function renderSummary(data,dong=''){currentData=data; currentDong=dong||''; title.textContent=[areaName(),currentDong?dongDisplayName(currentDong):'',typeName(data.propertyType||typeSelect.value)].filter(Boolean).join(' · '); const summary=data.summary||{}; const rentValue = summary.medianMonthlyRentWon; const depositValue = summary.medianDepositWon; metricRent.innerHTML=rentValue==null?'数据不足':moneyHtml(rentValue); metricDeposit.innerHTML=depositValue==null?'数据不足':moneyHtml(depositValue); metricContracts.textContent=Number(summary.totalContracts||summary.contractCount||0).toLocaleString('zh-CN'); const change=Number(summary.quarterChangePct); metricChange.textContent=Number.isFinite(change)?`${change>0?'+':''}${change.toFixed(1)}%`:'数据不足'; dataThrough.textContent=summary.dataThroughMonth?`数据截至 ${KHGDate.formatMonth(summary.dataThroughMonth,'zh-CN')}`:'最近已完成月份'; renderBuildings(data.buildings||[]); const count=Number(summary.totalContracts||summary.contractCount||0); status.textContent=count?`基于最近 ${summary.monthsUsed||6} 个完整月份${currentDong?`中 ${dongDisplayName(currentDong)}`:''}的 ${count.toLocaleString('zh-CN')} 笔官方申报合同。${LISTING_NOTE}`:'近期官方申报交易不足，暂时无法形成可靠的市场参考。'; status.className=`market-status ${count?'success':''}`; if(currentAreaData)renderDongs(currentAreaData.dongs||[]); updateLanguageSwitch();}

function renderBuildings(buildings){const buildingSection=document.querySelector('.building-section'); if(!currentDong){if(buildingSection)buildingSection.hidden=true;buildingList.innerHTML='';return;} if(buildingSection)buildingSection.hidden=false; if(!buildings.length){buildingList.innerHTML='<div class="explorer-empty">近期官方数据中没有可识别名称的建筑。</div>';return;} buildingList.innerHTML=buildings.slice(0,30).map(item=>{const dong=item.dong||currentDong; const interactiveParams=new URLSearchParams({lawdCd:areaSelect.value,type:typeSelect.value}); if(dong)interactiveParams.set('dong',dong); interactiveParams.set('buildingKey',item.buildingKey); const interactiveHref=`/zh/explore/building/?${interactiveParams.toString()}`; const seoHref=KHGExplorer.buildBuildingSeoUrl({lawdCd:areaSelect.value,type:typeSelect.value,dong,buildingName:item.buildingName,buildingKey:item.buildingKey,lang:'zh'}); const location=[dong?dongDisplayName(dong):'',areaName(),typeName()].filter(Boolean).join(' · '); const nameDisplay=KHGBuildingNames.getBuildingNameDisplay(item.buildingName,'zh'); return `<article class="building-row"><div class="building-name"><strong>${escapeHtml(nameDisplay.primary)}</strong>${nameDisplay.secondary?`<small class="building-official-name">${escapeHtml(nameDisplay.secondary)}</small>`:''}<small>${escapeHtml(location)}</small></div><div><span class="mobile-label">典型面积</span><strong>${formatArea(item.typicalAreaSqm)}</strong></div>${(()=>{const band=representativeBand(item); const rentValue=band?band.medianMonthlyRentWon:(item.contextualMedianMonthlyRentWon??item.medianMonthlyRentWon); const depositValue=band?band.medianDepositWon:(item.contextualMedianDepositWon??item.medianDepositWon); return `<div class="building-money"><span class="mobile-label">参考月租</span><strong>${rentValue==null?'—':moneyHtml(rentValue)}</strong></div><div class="building-money"><span class="mobile-label">参考押金</span><strong>${depositValue==null?'—':moneyHtml(depositValue)}</strong></div>`;})()}<div><span class="mobile-label">成交</span><strong>${Number(item.contractCount||0).toLocaleString('zh-CN')}</strong></div><div class="building-actions"><a href="${escapeHtml(seoHref)}">查看建筑页面 →</a><a class="secondary" href="${escapeHtml(interactiveHref)}">交互查看</a></div></article>`;}).join('');}

async function loadFx(){if(!currencySelect)return;currencySelect.disabled=true;try{const response=await fetch('/api/fx');const data=await response.json();if(!response.ok)throw new Error('FX unavailable');fxRates=data.rates||{};if(!fxRates[currencySelect.value]&&currencySelect.value!=='KRW')currencySelect.value='KRW';}catch(_){fxRates={};currencySelect.value='KRW';}finally{currencySelect.disabled=false;}}
function setLoading(message='正在加载官方租赁成交数据…'){status.textContent=message;status.className='market-status loading';buildingList.innerHTML='<div class="explorer-empty">正在加载建筑…</div>';exploreButton.disabled=true;}
async function loadDong(dong){currentDong=String(dong||'').trim();if(!currentDong)return;setLoading(`正在加载 ${dongDisplayName(currentDong)} 的官方租赁成交数据…`);updateLanguageSwitch();try{const params=currentParams(true);const response=await fetch(`/api/explore-dong?${params.toString()}`);const data=await response.json();if(!response.ok)throw new Error(data.error||'Neighborhood data failed');renderSummary(data,data.dong||currentDong);history.replaceState(null,'',`/zh/explore/?${currentParams(false).toString()}`);}catch(_){status.textContent='该街区的官方成交数据暂时无法加载，请稍后再试。';status.className='market-status error';buildingList.innerHTML='<div class="explorer-empty">目前无法加载该街区的建筑成交数据。</div>';}finally{exploreButton.disabled=false;}}
async function loadArea({requestedDong=''}={}){currentDong=String(requestedDong||'').trim();setLoading();try{const apiParams=new URLSearchParams({lawdCd:areaSelect.value,type:typeSelect.value});const response=areaSelect.value==='all'?await fetch(`/api/explore-seoul?type=${encodeURIComponent(typeSelect.value)}`):await fetch(`/api/explore-area?${apiParams.toString()}`);const data=await response.json();if(!response.ok)throw new Error(data.error||'Explorer data failed');currentAreaData=data;renderDongs(data.dongs||[]);const hasRequestedDong=areaSelect.value!=='all'&&currentDong&&(data.dongs||[]).some(item=>item.dong===currentDong);if(hasRequestedDong){await loadDong(currentDong);return;}currentDong='';renderSummary(data,'');history.replaceState(null,'',`/zh/explore/?${currentParams(false).toString()}`);}catch(_){currentAreaData=null;currentData=null;currentDong='';status.textContent='官方成交数据暂时无法加载，请稍后再试。';status.className='market-status error';metricRent.textContent='—';metricDeposit.textContent='—';metricContracts.textContent='—';metricChange.textContent='—';if(dongList)dongList.innerHTML='<div class="explorer-empty">街区数据暂时不可用。</div>';buildingList.innerHTML='<div class="explorer-empty">目前无法加载建筑级成交数据。</div>';}finally{exploreButton.disabled=false;}}
function applyQuerySelection(){const query=new URLSearchParams(location.search);const area=query.get('lawdCd');const type=query.get('type');const dong=query.get('dong')||'';const maxRent=query.get('maxRent')||'';const maxDeposit=query.get('maxDeposit')||'';if([...areaSelect.options].some(option=>option.value===area))areaSelect.value=area;if([...typeSelect.options].some(option=>option.value===type))typeSelect.value=type;if(maxRentSelect&&[...maxRentSelect.options].some(option=>option.value===maxRent))maxRentSelect.value=maxRent;if(maxDepositSelect&&[...maxDepositSelect.options].some(option=>option.value===maxDeposit))maxDepositSelect.value=maxDeposit;currentDong=dong;updateLanguageSwitch();return dong;}
exploreButton.addEventListener('click',()=>loadArea());areaSelect.addEventListener('change',()=>loadArea());typeSelect.addEventListener('change',()=>loadArea());if(maxRentSelect)maxRentSelect.addEventListener('change',()=>loadArea());if(maxDepositSelect)maxDepositSelect.addEventListener('change',()=>loadArea());document.querySelectorAll('[data-explore-area]').forEach(button=>button.addEventListener('click',()=>{areaSelect.value=button.dataset.exploreArea;loadArea();}));if(currencySelect)currencySelect.addEventListener('change',()=>{if(currentAreaData)renderDongs(currentAreaData.dongs||[]);if(currentData)renderSummary(currentData,currentDong);});
(async()=>{const requestedDong=applyQuerySelection();await loadFx();await loadArea({requestedDong});})();
