export type StoryCity = 'seoul' | 'singapore' | 'dubai' | 'tokyo';
export type StoryLocale = 'en' | 'ko';
export type StoryText = Readonly<{ en: string; ko: string }>;
export type StoryLink = Readonly<{ href: string; label: StoryText }>;
export type StorySection = Readonly<{ id: string; title: StoryText; paragraphs: Readonly<{ en: readonly string[]; ko: readonly string[] }>; links: readonly StoryLink[] }>;
export type CityStory = Readonly<{ city: StoryCity; name: StoryText; title: StoryText; deck: StoryText; sections: readonly [StorySection, StorySection, StorySection, StorySection, StorySection, StorySection]; sources: readonly { title: string; href: string }[] }>;

export const STORY_STEPS = [
  { id: 'discover', label: { en: 'Discover', ko: '도시의 매력' }, question: { en: 'What would life here feel like?', ko: '여기서 살면 어떤 일상일까?' } },
  { id: 'why-buy', label: { en: 'Why buy?', ko: '집을 가질 이유' }, question: { en: 'Does owning fit your plans?', ko: '나에게 집을 갖는 의미는?' } },
  { id: 'can-i-buy', label: { en: 'Can I buy?', ko: '구매 가능성' }, question: { en: 'What is possible for you?', ko: '내 자금으로 어디까지 가능할까?' } },
  { id: 'where', label: { en: 'Where?', ko: '지역 선택' }, question: { en: 'Which neighbourhood fits?', ko: '어느 동네가 나에게 맞을까?' } },
  { id: 'which-home', label: { en: 'Which home?', ko: '집 선택' }, question: { en: 'What makes a good shortlist?', ko: '어떤 집을 후보로 남길까?' } },
  { id: 'make-it-happen', label: { en: 'Make it happen', ko: '자금과 구매' }, question: { en: 'How do you get to the keys?', ko: '자금 마련부터 계약까지 어떻게?' } },
] as const;

export function cityStoryHref(city: StoryCity, locale: StoryLocale = 'en') { return `${locale === 'ko' ? '/ko' : ''}/news/city-stories/${city}/`; }

export const CITY_STORIES: readonly [CityStory, ...CityStory[]] = [
  {
    city: 'seoul', name: { en: 'Seoul', ko: '서울' },
    title: { en: 'If Seongsu feels like your neighbourhood, start here', ko: '성수가 좋아서, 서울의 집을 찾기 시작했다면' },
    deck: { en: 'From a favourite street to a place of your own: the everyday choices behind a Seoul home.', ko: '좋아하는 거리에서 나의 집으로. 동네의 분위기와 실제 예산 사이를 차근차근 좁혀가는 서울 이야기.' },
    sections: [
      { id: 'discover', title: { en: 'From the cafe street to your front door', ko: '카페 거리에서 집 앞 골목으로' }, paragraphs: {
        en: ['Seongsu makes a persuasive first impression. Along Yeonmujang-gil, cafes share the neighbourhood with handmade-shoe workshops; Ttukseom and Seongsu stations put it on Line 2. Seoul Forest offers another way to spend an afternoon, away from the shopfronts.', 'A favourite weekend neighbourhood becomes a different proposition when you imagine an ordinary Tuesday. Follow the route from the station to the residential streets. Where would you buy groceries, leave a bicycle, or take a late walk? Those small routines begin to turn a place you like into somewhere you might live.'],
        ko: ['성수에 마음이 가는 이유는 가격표만으로 설명되지 않는다. 연무장길에는 카페와 수제화 작업장이 함께 있고, 뚝섬역과 성수역으로 이어지는 2호선이 동네의 한 축을 이룬다. 서울숲에서는 상점이 이어지는 거리와 또 다른 오후를 보낼 수 있다.', '주말에 좋아하던 동네를 평일의 집으로 생각하면 보는 곳도 달라진다. 역에서 주거 골목까지 어떤 길로 걸을지, 장은 어디서 볼지, 늦은 저녁에는 어디를 산책할지. 집을 찾는 일은 그렇게 좋아하는 장소를 자신의 생활과 맞춰보는 데서 시작된다.'],
      }, links: [{ href: '/kr/seoul/', label: { en: 'Get to know the Seoul market', ko: '서울 주택 시장 살펴보기' } }] },
      { id: 'why-buy', title: { en: 'A home worth keeping, for your own reasons', ko: '이 동네에 집을 갖고 싶은 이유' }, paragraphs: {
        en: ['Perhaps you want a stable base near work, space for a growing household, or a place you can make your own. Put that reason into words before letting a price forecast make the decision for you.', 'Then give the plan a time horizon. How long do you expect to stay? What would change if your job or household changed? Compare owning with renting a similar home, including the cash tied up, interest, upkeep and the cost of moving again. The right purchase should leave room for the rest of your life.'],
        ko: ['직장과 가까운 곳에 오래 머물고 싶을 수도 있고, 가족에게 필요한 공간을 안정적으로 확보하고 싶을 수도 있다. 마음대로 고쳐 살 수 있는 내 집이 필요할 수도 있다. 가격 전망을 보기 전에, 자신이 이곳에 집을 갖고 싶은 이유부터 한 문장으로 적어보자.', '다음은 시간이다. 얼마나 오래 살 계획인지, 직장이나 가족 구성이 바뀌면 어떻게 할지 생각해 본다. 비슷한 집을 임차하는 경우와 자기자금·이자·유지비·다음 이사 비용을 함께 비교하면, 구매가 내 생활에 맞는 선택인지 더 선명해진다.'],
      }, links: [{ href: '/tools/property-scenario/', label: { en: 'Build your ownership-cost scenario', ko: '내 조건으로 보유비용 계산하기' } }] },
      { id: 'can-i-buy', title: { en: 'Start with available cash, then a price range', ko: '집값보다 먼저, 쓸 수 있는 현금을 정하기' }, paragraphs: {
        en: ['A purchase budget starts with the money you can commit without using every reserve. Separate the deposit and balance from taxes, fees, repairs and the cash you want to keep after moving. Ask a lender about your own eligibility before treating a possible loan as available money.', 'To see how a budget changes the map, begin with a clearly defined comparison. Our Seoul-wide study of recent 59-square-metre apartment sales below KRW 700 million offers one starting point. Carry the same size and time period into your own search rather than comparing whichever headline prices happen to appear.'],
        ko: ['예산은 통장 잔액 전부를 집값에 맞추는 방식으로 잡지 않는 편이 좋다. 계약금과 잔금, 세금과 수수료, 수리·이사 비용을 나누고 입주 후 남겨둘 현금도 정해보자. 대출은 본인의 조건을 금융기관에 확인한 금액부터 계획에 넣는다.', '예산이 지도를 어떻게 바꾸는지 보려면 비교 조건을 먼저 고정하면 된다. 서울 전체의 최근 전용 59㎡·7억원 이하 아파트 거래를 살펴본 글처럼, 면적과 기간을 맞춰 선택지를 보는 것이다. 같은 조건으로 관심 지역을 좁혀가면 막연했던 가격 차이가 읽히기 시작한다.'],
      }, links: [{ href: '/news/seoul-59sqm-under-700-million-2026/', label: { en: 'See recent Seoul sales below KRW 700m', ko: '서울 59㎡·7억원 이하 실거래 읽기' } }, { href: '/guides/buy-property-in-korea-as-foreigner/', label: { en: 'Check the buying sequence', ko: '외국인 매수 절차 확인하기' } }] },
      { id: 'where', title: { en: 'Keep the life you want; widen the search', ko: '좋아하는 생활을 남기고, 후보 지역을 넓히기' }, paragraphs: {
        en: ['What is the part of Seongsu you most want to keep: access to work, the park, the streets, or a particular kind of home? Choose two essentials. This makes it easier to compare a smaller home in your preferred area with more space elsewhere.', 'Place two preferred neighbourhoods and one alternative beside each other. Use the same housing type, size and transaction period. Add the journey to the places you actually visit. A useful comparison ends with a shortlist you can explain, not simply the lowest number on a map.'],
        ko: ['성수에서 가장 놓치고 싶지 않은 것은 무엇일까. 출퇴근 동선, 공원, 거리의 분위기, 특정한 주거 형태 중 우선순위 두 가지를 골라보자. 그러면 선호 지역의 작은 집과 다른 지역의 넓은 집을 비교할 기준이 생긴다.', '마음에 드는 지역 두 곳과 대안 한 곳을 나란히 놓고 같은 주택 유형·면적·거래 기간으로 비교한다. 여기에 실제로 자주 가는 곳까지의 이동을 더한다. 지도에서 가장 싼 곳을 찾는 것보다, 왜 이 세 곳을 남겼는지 설명할 수 있는 목록이 유용하다.'],
      }, links: [{ href: '/kr/seoul/explore/', label: { en: 'Compare neighbourhoods in Explore', ko: 'Explore에서 지역과 가격 비교하기' } }] },
      { id: 'which-home', title: { en: 'Give each shortlisted home the same questions', ko: '마음에 드는 집에도 같은 질문을 하기' }, paragraphs: {
        en: ['Once a building catches your eye, slow the comparison down. Match the floor area, floor, building age and contract date before deciding that one sale proves the asking price. Look at several transactions and whether the building trades often enough to support a comparison.', 'The visit has a different job from the price check. Light, noise, ventilation, storage, parking and the maintenance record can change how a home feels to live in. Keep these observations beside the numbers so an attractive interior does not make you forget the rest of the building.'],
        ko: ['마음에 드는 건물이 생기면 비교를 조금 더 세밀하게 한다. 전용면적과 층, 연식, 계약 시점을 맞추고 여러 거래를 살펴본다. 최근 한 건의 가격만으로 제시가격을 판단하기보다, 거래가 얼마나 이어졌는지도 같이 보는 것이다.', '방문할 때는 가격표가 답해주지 못하는 것을 확인한다. 채광과 소음, 환기와 수납, 주차, 건물 관리 상태를 적어두자. 숫자 옆에 생활의 기록이 남아 있으면 인상적인 인테리어 한 장에 판단이 치우치는 것을 줄일 수 있다.'],
      }, links: [{ href: '/kr/seoul/check/', label: { en: 'Check an asking price', ko: '제안받은 가격 확인하기' } }] },
      { id: 'make-it-happen', title: { en: 'Put the money and the dates on one page', ko: '자금과 지급일을 한 장에 놓기' }, paragraphs: {
        en: ['A workable purchase plan gives every payment a date and a source. Write down the deposit, interim payments if any, balance, borrowing, transfers and transaction costs. Check the documents and timing with the professionals handling the transaction before making a commitment.', 'At this point, the question is concrete: can this particular home fit the cash you can provide, the finance you can obtain and the life you want? The favourite street is still part of the decision. Now it sits alongside a budget and a plan you can act on.'],
        ko: ['구매 계획이 구체적이려면 돈마다 출처와 날짜가 있어야 한다. 계약금, 중도금이 있다면 그 지급일, 잔금, 대출 실행, 송금, 취득 부대비용을 한 장에 놓는다. 계약 전에 거래를 맡는 전문가와 서류·지급 순서를 확인하면 자금이 필요한 시점도 분명해진다.', '이제 질문은 구체적이다. 이 집이 내가 준비할 수 있는 현금, 실제 가능한 금융 조건, 앞으로 살고 싶은 생활에 함께 맞는가. 처음 마음에 들었던 거리는 그대로 남아 있다. 여기에 실행할 수 있는 예산과 일정이 더해지는 것이다.'],
      }, links: [{ href: '/guides/seoul-apartment-buying-budget-guide/', label: { en: 'Work through the Seoul buying budget', ko: '서울 매입 예산과 비용 정리하기' } }] },
    ],
    sources: [{ title: 'Seoul Metropolitan Government · Yeonmujang-gil', href: 'https://english.seoul.go.kr/yeonmujang-gil-seongsu-dong-cafe-street/' }, { title: 'Seoul Metropolitan Government · Parks and riverside culture', href: 'https://english.seoul.go.kr/seoul-launches-citywide-outdoor-performances-musicals-at-seoul-plaza-opera-by-the-han-river/' }],
  },
  {
    city: 'singapore', name: { en: 'Singapore', ko: '싱가포르' },
    title: { en: 'In Singapore, begin with the neighbourhood between your journeys', ko: '싱가포르의 집, 역과 현관 사이에서 고르기' },
    deck: { en: 'The market, the food centre and the trip home can matter as much as the address on a condo brochure.', ko: '콘도 이름보다 먼저 떠올릴 것들. 장을 보는 시장, 가까운 식사 장소, 역에서 집까지 이어지는 길.' },
    sections: [
      { id: 'discover', title: { en: 'A neighbourhood you can use every day', ko: '매일 이용할 수 있는 동네의 매력' }, paragraphs: { en: ['Tiong Bahru brings homes, small shops and places to eat into the same neighbourhood. Its market and food centre make a useful starting point for thinking about an ordinary day rather than a property brochure.', 'Try that view of the city wherever you search. Singapore’s feeder buses connect housing areas with MRT stations and bus interchanges. Look beyond the station name to the final part of the journey: the walk, the bus connection and the errands you can combine on the way home.'], ko: ['티옹바루에서는 주거동과 개별 상점, 음식을 파는 장소가 동네 안에 함께 놓여 있다. 시장과 푸드센터를 중심에 두고 보면 집의 매력도 조금 다르게 읽힌다. 평소 어디서 장보고 식사할지를 떠올리는 것만으로도 생활의 모습이 구체적이 된다.', '다른 지역에서도 같은 시선이 유용하다. 싱가포르의 지선버스는 주거단지와 MRT역·버스환승장을 연결한다. 역 이름에서 멈추지 않고 집까지 남은 길, 환승, 돌아오는 길에 해결할 수 있는 일을 살펴보자.'] }, links: [{ href: '/sg/singapore/', label: { en: 'Explore Singapore’s housing market', ko: '싱가포르 주택 시장 살펴보기' } }] },
      { id: 'why-buy', title: { en: 'Choose the role the home will play', ko: '이 집이 생활에서 맡을 역할' }, paragraphs: { en: ['A long-term family home and a property held for rental income need different comparisons. Write down your likely stay, household needs and the flexibility you want before deciding how much of your budget to commit.', 'For an ownership comparison, include the costs of buying, financing, maintaining and eventually selling. For a home to live in, put useful space and daily journeys beside that calculation.'], ko: ['오래 살 가족의 집과 임대수입을 기대하는 주택은 비교 기준이 달라진다. 예상 거주기간과 가족에게 필요한 공간, 앞으로 이동할 가능성을 먼저 적어보자.', '소유 비용을 비교할 때는 취득·금융·관리·향후 매도 비용까지 함께 본다. 직접 살 집이라면 실제로 쓰는 공간과 매일의 이동을 그 계산 옆에 놓는다.'] }, links: [{ href: '/tools/property-scenario/?market=sg-singapore&currency=SGD', label: { en: 'Compare the ownership costs', ko: '싱가포르 보유비용 계산하기' } }] },
      { id: 'can-i-buy', title: { en: 'Your buyer profile comes before the shortlist', ko: '매수자 조건부터 예산에 반영하기' }, paragraphs: { en: ['Citizenship, residency and household circumstances can change which housing options and duties need checking. Establish your own position before comparing a headline condo price with an HDB resale price.', 'Keep purchase price, duties, fees and available financing in separate rows. A lender’s confirmation and the current official eligibility guidance make a more useful budget than a rule of thumb borrowed from another buyer.'], ko: ['국적과 거주 신분, 가족 구성에 따라 확인할 주택 유형과 세금 조건이 달라질 수 있다. 콘도와 HDB 재판매 가격을 나란히 보기 전에 자신의 매수 조건을 먼저 정리하자.', '매매가격과 세금, 수수료, 실제 가능한 금융 조건을 나누어 적는다. 다른 사람의 경험에서 가져온 비율보다 금융기관의 확인과 현재 공식 자격 안내가 내 예산을 잡는 데 유용하다.'] }, links: [{ href: '/news/policy/singapore-absd-policy-status/', label: { en: 'Check buyer-profile and duty questions', ko: '매수자 조건과 세금 확인하기' } }] },
      { id: 'where', title: { en: 'Make CCR, RCR and OCR meaningful to your life', ko: 'CCR·RCR·OCR을 나의 생활로 읽기' }, paragraphs: { en: ['The three region labels are a starting map. Turn them into a comparison of specific neighbourhoods, routes and homes. A smaller central apartment and a larger home farther out may serve very different routines.', 'Keep the sale type and period consistent when comparing prices. Then add the features you would use often, rather than paying for a long list you rarely need.'], ko: ['CCR·RCR·OCR이라는 구분은 첫 지도다. 실제 선택은 구체적인 동네와 이동 경로, 집의 조건을 비교할 때 시작된다. 중심지의 작은 집과 외곽의 넓은 집이 어떤 일상에 맞을지 생각해 보자.', '가격을 비교할 때는 거래 유형과 기간을 맞춘다. 여기에 자주 사용할 생활 조건을 더하면, 길게 나열된 시설보다 자신에게 필요한 것이 무엇인지 분명해진다.'] }, links: [{ href: '/news/singapore-ccr-rcr-ocr-comparison/', label: { en: 'Compare the three regions', ko: '세 지역의 실제 가격 비교하기' } }] },
      { id: 'which-home', title: { en: 'Look beyond the show-flat impression', ko: '집 안의 첫인상 다음에 확인할 것' }, paragraphs: { en: ['Check the usable layout, tenure, age and maintenance alongside recent comparable transactions. A new launch and a completed resale home also put demands on your money at different times.', 'A short list is most useful when every project answers the same questions. Keep the price evidence, monthly commitments and the features you will actually use together.'], ko: ['실제로 쓸 수 있는 평면과 소유 형태, 연식, 관리 상태를 최근 유사 거래와 함께 본다. 신규 분양과 완공된 재판매 주택은 자금이 필요한 시점도 다르다.', '후보 목록에는 모든 단지에 같은 질문을 남겨보자. 가격의 근거와 매달 부담, 실제 사용할 시설을 함께 적으면 비교가 한결 쉬워진다.'] }, links: [{ href: '/sg/singapore/explore/', label: { en: 'Find and compare projects', ko: '단지와 거래 비교하기' } }, { href: '/sg/singapore/check/', label: { en: 'Check a project offer', ko: '제시가격 확인하기' } }] },
      { id: 'make-it-happen', title: { en: 'Give the purchase a cash timeline', ko: '구매 절차를 현금의 시간표로 바꾸기' }, paragraphs: { en: ['Put deposits, duties, legal costs, loan drawdown and the balance on one timeline. Confirm the conditions and payment dates for the property you have chosen.', 'Leave an operating reserve after completion. A home that fits the purchase budget should also fit the way you intend to live in it.'], ko: ['계약금과 세금, 법률 비용, 대출 실행, 잔금 지급을 하나의 일정에 적어보자. 선택한 주택의 계약 조건과 실제 지급일을 확인하면서 금액을 채운다.', '입주 후 사용할 여유자금도 남겨둔다. 계약할 수 있는 집에서 한 걸음 더 나아가, 계획한 생활을 이어갈 수 있는 집인지 확인하는 단계다.'] }, links: [{ href: '/guides/singapore-condo-buying-budget-guide/', label: { en: 'Plan the Singapore buying budget', ko: '싱가포르 매입 예산 정리하기' } }] },
    ], sources: [{ title: 'National Heritage Board · Tiong Bahru Heritage Trail', href: 'https://www.roots.gov.sg/places/places-landing/trails/tiong-bahru-heritage-trail' }, { title: 'Land Transport Authority · Bus Network', href: 'https://www.lta.gov.sg/content/ltagov/en/getting_around/public_transport/bus_network.html' }],
  },
  {
    city: 'dubai', name: { en: 'Dubai', ko: '두바이' }, title: { en: 'Choose a Dubai home for the days between the skyline views', ko: '두바이의 집, 전망 다음의 일상을 고르기' }, deck: { en: 'From Marina to the city beyond: connect the address you like with the costs and timing of owning it.', ko: '마리나의 풍경에서 실제 생활로. 마음에 드는 주소를 보유비용과 입주 계획에 맞춰보는 여정.' },
    sections: [
      { id: 'discover', title: { en: 'Picture the trip home, too', ko: '전망과 함께, 집으로 돌아오는 길을 보기' }, paragraphs: { en: ['Dubai Marina’s towers and waterfront and Downtown’s city landmarks offer different settings for a home. Begin with the places you would actually use: work, groceries, exercise and the people you see regularly.', 'Map those journeys before choosing a building for its view. Check the full trip from the front door, the transport you plan to use and the parts of the neighbourhood you would return to on an ordinary evening.'], ko: ['고층 건물과 수변이 있는 마리나, 도시의 대표 시설이 모인 다운타운은 서로 다른 생활의 배경이 된다. 집을 고를 때는 직장과 장보는 곳, 운동하는 장소, 자주 만날 사람을 먼저 지도에 놓아보자.', '전망이 마음에 드는 건물을 발견했다면 현관에서 시작하는 이동도 확인한다. 어떤 교통수단을 쓸지, 평일 저녁에 다시 찾을 장소는 어디인지 생각하면 두바이의 지도가 생활의 지도로 바뀐다.'] }, links: [{ href: '/ae/dubai/', label: { en: 'Get to know the Dubai market', ko: '두바이 시장 살펴보기' } }] },
      { id: 'why-buy', title: { en: 'A rental return should leave something after the bills', ko: '임대수익에서 비용을 빼고도 남는 것' }, paragraphs: { en: ['If rental income is part of the plan, start with the money left after service charges, repairs, management and vacant periods. A headline yield does not tell you how much cash the property will provide.', 'If you plan to live there, compare the ownership costs with renting a similar home for your expected stay. Your intended use makes the numbers meaningful.'], ko: ['임대수입을 기대한다면 관리비와 수선비, 관리 대행비, 공실을 반영한 뒤 남는 돈부터 본다. 제시된 수익률 한 숫자로 실제 현금흐름까지 알 수는 없다.', '직접 살 계획이라면 예상 거주기간 동안 비슷한 집을 임차하는 비용과 비교한다. 어떤 목적으로 보유할지가 숫자를 읽는 기준이 된다.'] }, links: [{ href: '/news/dubai-rental-yield-after-costs/', label: { en: 'Read the costs behind rental yield', ko: '두바이 임대수익과 비용 읽기' } }] },
      { id: 'can-i-buy', title: { en: 'Set a budget for the property you can actually purchase', ko: '실제로 매수할 수 있는 집의 예산 잡기' }, paragraphs: { en: ['Confirm ownership eligibility for the specific location and property, then separate the purchase price from registration, professional fees and finance. Establish the cash available at each payment stage.', 'A Ready home and an Off-Plan contract have different timing and evidence. Keep that distinction in the budget from the beginning.'], ko: ['해당 지역과 부동산의 소유 자격을 먼저 확인하고, 매입가격과 등록·전문가 비용, 금융비용을 나누어 본다. 지급 단계마다 준비할 수 있는 현금도 확인한다.', '완공 주택인 Ready와 분양 계약인 Off-Plan은 일정과 확인할 근거가 다르다. 예산을 잡을 때부터 두 경우를 구분해 두자.'] }, links: [{ href: '/guides/dubai-ready-apartment-buying-budget-guide/', label: { en: 'Work through a Ready-apartment budget', ko: '두바이 완공 아파트 예산 살펴보기' } }] },
      { id: 'where', title: { en: 'Compare the area as it is today', ko: '오늘의 동네와 앞으로의 계획을 함께 보기' }, paragraphs: { en: ['Put delivered homes, rental activity and the facilities already operating beside the plans for an area. A development announcement answers a different question from evidence of people moving in.', 'Use area-level records to narrow the map, keeping Ready and Off-Plan transactions separate. Then check the buildings and streets that would matter to you.'], ko: ['이미 인도된 주택과 임대 활동, 현재 운영 중인 생활시설을 앞으로의 개발 계획 옆에 놓는다. 개발 발표와 실제 입주가 각각 무엇을 보여주는지 나누어 읽는 것이다.', '지역별 기록으로 지도를 좁히되 Ready와 Off-Plan 거래는 구분한다. 그다음 자신의 생활과 관계있는 건물과 거리를 확인한다.'] }, links: [{ href: '/ae/dubai/explore/', label: { en: 'Compare Dubai areas', ko: '두바이 지역 비교하기' } }] },
      { id: 'which-home', title: { en: 'Ask what the building will cost to keep', ko: '이 건물을 유지하는 데 드는 비용 묻기' }, paragraphs: { en: ['Request the service-charge basis, maintenance information and the documents relevant to the sale. Check the condition and usable layout of a completed home; for Off-Plan, examine the project, contract and payment schedule.', 'Keep these notes beside the price comparison. Two homes at the same price can place different demands on your annual budget.'], ko: ['관리비 부과 기준과 유지보수 정보, 거래에 필요한 서류를 확인한다. 완공 주택은 실제 상태와 평면을 보고, 분양 주택은 사업과 계약, 지급 일정을 살펴본다.', '가격 비교 옆에 이 기록을 남겨두자. 매매가격이 같은 두 집도 매년 필요한 예산은 달라질 수 있다.'] }, links: [{ href: '/ae/dubai/check/', label: { en: 'Check price and gross yield', ko: '가격과 예상 임대수익 확인하기' } }] },
      { id: 'make-it-happen', title: { en: 'Test the plan against a later handover', ko: '입주가 늦어지는 경우까지 자금계획에 넣기' }, paragraphs: { en: ['Line up the contract payments, borrowing, transfer costs and cash reserve. If handover is in the future, work through what a delay would mean for rent, interest and your available cash.', 'Before committing, have the property-specific documents and payment arrangements checked. A clear schedule makes it easier to see whether the home and your plans can move together.'], ko: ['계약에 따른 지급액과 차입금, 송금 비용, 여유현금을 일정에 맞춘다. 앞으로 인도받을 집이라면 일정이 늦어질 때 추가 임대료와 이자, 현금 여력이 어떻게 달라지는지도 계산해 보자.', '계약 전에 해당 부동산의 서류와 지급 방식을 확인한다. 집의 일정과 자신의 계획이 함께 움직일 수 있는지 보는 마지막 단계다.'] }, links: [{ href: '/ae/dubai/guide/', label: { en: 'Prepare for a Dubai purchase', ko: '두바이 구매 절차 준비하기' } }] },
    ], sources: [{ title: 'Visit Dubai · Dubai Marina', href: 'https://www.visitdubai.com/en/explore-dubai/dubai-neighbourhoods/dubai-marina' }, { title: 'Visit Dubai · Downtown Dubai', href: 'https://www.visitdubai.com/en/explore-dubai/dubai-neighbourhoods/downtown-dubai' }],
  },
  {
    city: 'tokyo', name: { en: 'Tokyo', ko: '도쿄' }, title: { en: 'A Tokyo home starts with a station, and the streets beyond it', ko: '도쿄의 집, 역 이름 다음의 골목을 고르기' }, deck: { en: 'From Kagurazaka’s lanes to the condition of an apartment building: bring the neighbourhood and the purchase into the same picture.', ko: '카구라자카의 골목에서 맨션의 관리 상태까지. 좋아하는 동네와 오래 보유할 집을 함께 생각하는 도쿄 이야기.' },
    sections: [
      { id: 'discover', title: { en: 'Look at the streets beyond the station', ko: '역에서 나온 뒤 이어지는 생활' }, paragraphs: { en: ['Kagurazaka combines traditional restaurants and narrow lanes with cafes and shops. Kagurazaka, Iidabashi and Ushigome-Kagurazaka stations offer different approaches to the area; the route you use becomes part of how the neighbourhood feels.', 'Begin a Tokyo home search with the places you expect to visit each week. A line on the map and a station name are useful beginnings. The walk to your front door, nearby shopping and the streets you enjoy complete the picture.'], ko: ['카구라자카에는 전통 음식점과 골목, 카페와 상점이 함께 있다. 카구라자카역과 이다바시역, 우시고메카구라자카역은 동네로 들어가는 서로 다른 입구가 된다. 어느 길을 이용하느냐도 이곳에서의 생활을 바꾼다.', '도쿄에서 집을 찾는다면 매주 자주 갈 장소부터 적어보자. 노선과 역 이름은 출발점이다. 현관까지 이어지는 길과 장보는 곳, 좋아하는 골목을 더하면 실제로 살 동네의 모습이 보이기 시작한다.'] }, links: [{ href: '/jp/tokyo/', label: { en: 'Start exploring Tokyo', ko: '도쿄 살펴보기' } }] },
      { id: 'why-buy', title: { en: 'Think about the home you want to keep', ko: '오래 보유하고 싶은 집의 조건' }, paragraphs: { en: ['A base for your own life and a rental property have different funding and management needs. Decide which you are considering and how long you expect to hold it before comparing prices.', 'Include the work of ownership in that decision: maintenance, building management, time away from Japan and the possibility of selling. This turns a broad interest in Tokyo into a more useful brief for the home search.'], ko: ['직접 생활할 거점과 임대용 부동산은 자금과 관리 조건이 다르다. 어느 목적에 가까운지, 얼마나 오래 보유할 생각인지부터 정해보자.', '유지보수와 건물 관리, 일본을 비우는 기간, 나중에 매도할 가능성도 함께 생각한다. 도쿄에 대한 관심이 어떤 집을 찾을지에 대한 구체적인 기준으로 바뀌는 과정이다.'] }, links: [] },
      { id: 'can-i-buy', title: { en: 'Get a financing answer for your own circumstances', ko: '내 거주 상태와 목적에 맞는 금융 조건 확인하기' }, paragraphs: { en: ['Separate your residency position, purchase purpose and documented income when asking a lender about financing. A product for a foreign national without permanent residency is not necessarily a loan for someone living overseas.', 'For example, Tokyo Star Bank’s published Star Housing Loan conditions concern applicants resident in Japan and owner-occupied housing. Use the lender’s own terms to ask about your situation rather than extending another borrower’s approval to your purchase.'], ko: ['금융기관에 문의할 때는 거주 상태와 취득 목적, 증빙 가능한 소득을 나누어 설명한다. 영주권 없는 외국인을 대상으로 한 상품이 해외 거주자에게도 같은 조건으로 제공되는 것은 아니다.', '예를 들어 도쿄스타은행의 Star Housing Loan 안내는 일본 거주 신청자와 본인·가족의 주거 목적을 대상으로 조건을 설명한다. 다른 사람의 승인 사례보다 해당 금융기관의 현재 안내를 기준으로 자신의 경우를 확인하자.'] }, links: [{ href: 'https://www.tokyostarbank.co.jp/foreign/en/products/loan/homeloan_star/', label: { en: 'Read the lender’s eligibility information', ko: '은행의 상품·자격 안내 읽기' } }] },
      { id: 'where', title: { en: 'Narrow the city before comparing the homes', ko: '도쿄 전체에서 관심 지역으로 좁히기' }, paragraphs: { en: ['Choose a few neighbourhoods around the journeys and routines you want to keep. Compare similar apartment sizes and ages, and distinguish asking-price reports from completed-transaction records.', 'Keep the geography visible. A Tokyo prefecture average, a 23-ward figure and one neighbourhood are different starting points for a search.'], ko: ['유지하고 싶은 이동과 생활을 기준으로 몇 개 지역을 골라본다. 비슷한 면적과 연식으로 비교하고, 호가 조사와 실제 거래 기록도 나누어 읽는다.', '자료가 어느 범위를 말하는지 놓치지 말자. 도쿄도 전체, 23구, 특정 동네의 수치는 각각 다른 출발점이다.'] }, links: [{ href: '/jp/tokyo/explore/', label: { en: 'Open Tokyo area exploration', ko: '도쿄 지역 탐색 열기' } }] },
      { id: 'which-home', title: { en: 'Read the building as carefully as the apartment', ko: '집 안만큼 건물의 기록도 읽기' }, paragraphs: { en: ['An appealing renovated interior is one part of the purchase. Request the building’s maintenance history, long-term repair plan, reserve information and relevant assessments with professional help.', 'Put those records beside the apartment’s condition and comparable sales. This is how an older home’s attractive location and price can be considered alongside the commitments of owning it.'], ko: ['보기 좋게 수리한 실내는 구매 판단의 한 부분이다. 전문가의 도움을 받아 건물의 유지보수 이력과 장기수선계획, 적립금 정보, 관련 점검자료를 확인한다.', '그 기록을 집의 상태와 유사 거래 옆에 놓아보자. 구축의 입지와 가격이라는 매력을 앞으로 부담할 관리 의무와 함께 판단할 수 있다.'] }, links: [] },
      { id: 'make-it-happen', title: { en: 'Bring the payment and paperwork plans together', ko: '지급 일정과 서류 준비를 함께 맞추기' }, paragraphs: { en: ['Map the purchase payments, currency transfers, transaction costs and any loan drawdown before agreeing to dates. Ask the professionals handling the transaction which documents apply to your residence and ownership structure.', 'Japan’s Ministry of Finance publishes guidance on acquisition reporting by non-residents. Check the applicable reporting procedure separately from ownership registration, using your acquisition purpose and transaction details.'], ko: ['지급일을 확정하기 전에 매입대금과 환전·송금, 거래비용, 대출 실행을 일정에 놓아본다. 자신의 거주 상태와 소유 형태에 어떤 서류가 적용되는지 거래를 맡는 전문가에게 확인한다.', '일본 재무성은 비거주자의 부동산 취득 신고에 관한 안내를 제공한다. 취득 목적과 거래 내용을 정리한 뒤 적용되는 신고 절차를 확인하고, 소유권 등기와도 구분해 준비한다.'] }, links: [{ href: 'https://www.mof.go.jp/english/policy/international_policy/real_property/faq.pdf', label: { en: 'Read the Ministry of Finance acquisition-reporting FAQ', ko: '일본 재무성 취득 신고 안내 읽기' } }] },
    ], sources: [{ title: 'GO TOKYO · Kagurazaka', href: 'https://www.gotokyo.org/en/destinations/central-tokyo/kagurazaka/index.html' }, { title: 'Tokyo Star Bank · Star Housing Loan', href: 'https://www.tokyostarbank.co.jp/foreign/en/products/loan/homeloan_star/' }, { title: 'Ministry of Finance Japan · Acquisition-reporting FAQ', href: 'https://www.mof.go.jp/english/policy/international_policy/real_property/faq.pdf' }],
  },
];
