import type { NewsWorkspaceItem } from '../lib/news/news-workspace-model';

// Original pages checked on 2026-09-08. This is an editorial release, not an
// unreviewed RSS fallback. Publication dates belong to the original publisher.
// Photographs, provider tables and full article bodies are not reproduced.
export const REVIEWED_NEWS_CHECKED_AT = '2026-09-08';
export const REVIEWED_NEWS: readonly NewsWorkspaceItem[] = [
  {
    id: 'reviewed-seoul-starts-20260907', market: 'seoul', marketLabel: 'Seoul', category: 'Housing supply',
    title: 'Seoul housing starts rise through July', titleKo: '서울 주택 착공 증가, 실제 입주까지는 얼마나 남았을까?',
    summary: 'Seoul reported more housing starts in January–July than a year earlier, with redevelopment making up a substantial share of the apartment pipeline.',
    summaryKo: '서울의 1~7월 주택 착공이 전년 동기보다 늘었다. 아파트 착공에서는 정비사업이 큰 비중을 차지했다.',
    buyerNote: 'Look at the construction stage and expected handover in the district you are considering. A housing start is not a home ready to move into.',
    buyerNoteKo: '관심 지역의 공사 단계와 입주 일정을 함께 보자. 착공이 늘었다고 당장 선택할 수 있는 집이 늘어난 것은 아니다.',
    url: 'https://biz.heraldcorp.com/article/10864418', publisher: 'Herald Economy', publishedAt: '2026-09-07',
    internalHref: null, evidence: 'checking', evidenceLine: 'Publisher report checked against the Seoul Housing Portal announcement', sourceKind: 'reviewed-source',
  },
  {
    id: 'reviewed-jeonnong-20260902', market: 'seoul', marketLabel: 'Seoul', category: 'Neighbourhood change',
    title: 'Jeonnong redevelopment plan moves forward', titleKo: '전농동 재개발 기획 확정, 동네의 다음 변화는?',
    summary: 'Seoul finalised a redevelopment concept for Jeonnong-dong 152-65, combining new homes with road and pedestrian improvements.',
    summaryKo: '서울시는 전농동 152-65 일대 신속통합기획을 확정했다. 주택 공급과 도로·보행환경 개선을 함께 담은 계획이다.',
    buyerNote: 'Use the proposal to understand the neighbourhood direction, then check the remaining approvals and timing before treating it as future supply.',
    buyerNoteKo: '동네의 변화 방향을 읽을 수 있는 소식이다. 공급 시점까지 판단하려면 남은 인허가와 사업 진행을 더 확인해야 한다.',
    url: 'https://www.yna.co.kr/view/AKR20260902052000004', publisher: 'Yonhap News Agency', publishedAt: '2026-09-02',
    internalHref: null, evidence: 'checking', evidenceLine: 'Original public report checked', sourceKind: 'reviewed-source',
  },
  {
    id: 'reviewed-upper-changi-20260904', market: 'singapore', marketLabel: 'Singapore', category: 'New developments',
    title: 'New Upper Changi housing site awarded', titleKo: '뉴 어퍼 창이 주택 부지 낙찰, 동부에 더해질 선택지',
    summary: 'URA awarded the New Upper Changi Road residential site to United Venture Development (Daisy) and CL Sapphire on a 99-year lease.',
    summaryKo: 'URA는 뉴 어퍼 창이 로드의 99년 임차권 주거 부지를 유나이티드 벤처 디벨롭먼트와 CL 사파이어에 낙찰했다.',
    buyerNote: 'The land award adds a future project to the eastern supply pipeline. A developer’s land bid is not an announced apartment price.',
    buyerNoteKo: '싱가포르 동부의 향후 공급을 살펴볼 수 있다. 토지 낙찰가와 앞으로 발표될 아파트 분양가는 구분해서 읽자.',
    url: 'https://www.ura.gov.sg/news/media/pr26-64/', publisher: 'Urban Redevelopment Authority', publishedAt: '2026-09-04',
    internalHref: null, evidence: 'checking', evidenceLine: 'Original URA announcement checked', sourceKind: 'reviewed-source',
  },
  {
    id: 'reviewed-marina-orchard-20260813', market: 'singapore', marketLabel: 'Singapore', category: 'Housing supply',
    title: 'New housing sites in Marina South and Orchard', titleKo: '마리나 사우스와 오차드, 신규 주택 부지 공개',
    summary: 'URA released residential sites at Marina Gardens Lane and Orchard Boulevard under its second-half land-sales programme, both near MRT stations.',
    summaryKo: 'URA는 하반기 토지공급 프로그램에 따라 MRT역 인근 마리나 가든스 레인과 오차드 불러바드의 주거 부지를 공개했다.',
    buyerNote: 'Compare future central-area supply with existing homes, while keeping tender sites separate from completed homes and confirmed launch dates.',
    buyerNoteKo: '도심의 기존 주택과 향후 공급을 비교해 보자. 토지 공급, 분양, 준공은 각각 다른 단계다.',
    url: 'https://www.ura.gov.sg/news/media/pr26-62/', publisher: 'Urban Redevelopment Authority', publishedAt: '2026-08-13',
    internalHref: null, evidence: 'checking', evidenceLine: 'Original URA announcement checked', sourceKind: 'reviewed-source',
  },
  {
    id: 'reviewed-dubai-completions-20260907', market: 'dubai', marketLabel: 'Dubai', category: 'Delivered supply',
    title: 'Dubai reports first-half property completions', titleKo: '두바이 상반기 준공 실적, 내 관심 지역에도 공급이 늘었을까?',
    summary: 'DLD reported completed projects and additional property units in the first half of 2026, alongside progress in its first-time buyer programme.',
    summaryKo: 'DLD는 2026년 상반기 부동산 프로젝트 준공과 추가 유닛 공급, 생애최초 주택 구매 지원 실적을 공개했다.',
    buyerNote: 'Break citywide totals down by area and property type. They cannot establish a particular building’s demand, vacancy or rental return.',
    buyerNoteKo: '도시 전체 수치를 지역과 유형으로 나눠볼 필요가 있다. 전체 준공 물량이 특정 건물의 임대수요나 수익률을 말해주지는 않는다.',
    url: 'https://dubailand.gov.ae/en/news-media/dubai-land-department-advances-investor-confidence-innovation-and-emirati-empowerment-at-ips-2026-expanding-real-estate-opportunities/', publisher: 'Dubai Land Department', publishedAt: '2026-09-07',
    internalHref: null, evidence: 'checking', evidenceLine: 'Original DLD announcement checked; units are not all classified as apartments', sourceKind: 'reviewed-source',
  },
  {
    id: 'reviewed-dubai-registration-20260903', market: 'dubai', marketLabel: 'Dubai', category: 'Buying process',
    title: 'Dubai connects project registration and escrow', titleKo: '두바이 사업 등록과 에스크로 관리, 하나의 절차로 연결',
    summary: 'DLD launched Initial Registration, bringing project registration, property transaction registration and escrow account management into a shared administrative process.',
    summaryKo: 'DLD는 사업 등록·부동산 거래 등록·에스크로 계좌 관리를 연결하는 Initial Registration 플랫폼을 출시했다.',
    buyerNote: 'Registration and escrow remain part of checking an off-plan project. A new administrative platform does not replace review of the project and contract.',
    buyerNoteKo: '분양 주택을 볼 때는 사업 등록과 에스크로 정보를 확인하자. 행정 시스템 개편이 개별 사업과 계약 검토를 대신하지는 않는다.',
    url: 'https://dubailand.gov.ae/en/news-media/dubai-land-department-launches-initial-registration-a-smarter-journey-for-developers-and-greater-efficiency-for-the-real-estate-sector', publisher: 'Dubai Land Department', publishedAt: '2026-09-03',
    internalHref: null, evidence: 'checking', evidenceLine: 'Original DLD announcement checked', sourceKind: 'reviewed-source',
  },
  {
    id: 'reviewed-tokyo-wards-20260901', market: 'tokyo', marketLabel: 'Tokyo', category: 'Neighbourhood prices',
    title: 'Tokyo resale pricing varies across wards', titleKo: '도쿄 아파트 가격, 평균보다 구별 차이를 볼 때',
    summary: 'Tokyo Kantei’s first-half report compares existing apartments selected within stated building-age and station-walking-distance bands, showing different price movements across the 23 wards.',
    summaryKo: '도쿄칸테이는 연식과 역 접근성 등의 조건을 맞춰 기존 아파트를 비교했다. 도쿄 23구 안에서도 지역별 가격 움직임이 달랐다.',
    buyerNote: 'Read the provider’s sample and method before comparing wards. Compare the report’s selection criteria with the homes in your own shortlist.',
    buyerNoteKo: '관심 구를 비교하기 전에 표본과 조사 방법부터 읽자. 연식·역 도보거리 조건을 맞춘 표본이 내 후보 주택과 얼마나 비슷한지 확인하자.',
    url: 'https://www.kantei.ne.jp/news/release/9375/', publisher: 'Tokyo Kantei', publishedAt: '2026-09-01',
    internalHref: null, evidence: 'checking', evidenceLine: 'Original report checked; no provider table or dataset reproduced', sourceKind: 'reviewed-source',
  },
  {
    id: 'reviewed-tokyo-asking-20260824', market: 'tokyo', marketLabel: 'Tokyo', category: 'Asking prices',
    title: 'Tokyo ward apartment asking prices edge lower', titleKo: '도쿄 23구 아파트 호가 소폭 하락, 거래가격도 같을까?',
    summary: 'Tokyo Kantei’s July survey recorded a small monthly decline in the 70-square-metre equivalent asking price of existing apartments in Tokyo’s 23 wards.',
    summaryKo: '도쿄칸테이의 7월 조사에서 도쿄 23구 기존 아파트의 70㎡ 환산 호가가 전월보다 소폭 낮아졌다.',
    buyerNote: 'An asking-price movement can frame a question for negotiation. Check comparable completed transactions before drawing a conclusion about value.',
    buyerNoteKo: '호가 변화는 협상에서 던질 질문의 출발점이다. 가격 판단에는 조건이 비슷한 실제 거래를 함께 확인하자.',
    url: 'https://www.kantei.ne.jp/report/70m2/9297/', publisher: 'Tokyo Kantei', publishedAt: '2026-08-24',
    internalHref: null, evidence: 'checking', evidenceLine: 'Original July asking-price release checked, not transaction-price data', sourceKind: 'reviewed-source',
  },
];
