const currencySelect = document.querySelector('#currencySelect');
const currencyInputs = [...document.querySelectorAll('[data-currency-input]')];
let fxRates = {};
let activeInputCurrency = 'KRW';

function selectedCurrency(){ return currencySelect ? currencySelect.value : 'KRW'; }
function getInputWon(input){ const n=Number(input.dataset.krwValue || 0); return Number.isFinite(n)?n:0; }
function syncCurrencyInput(input){ const won=KHGCurrency.convertToKrw(Number(input.value||0),activeInputCurrency,fxRates); if(won!=null) input.dataset.krwValue=String(Math.round(won)); }
function moneyHtml(won){ return KHGCurrency.formatMoneyHtml(won,selectedCurrency(),fxRates,'en-US'); }
function renderCurrencyInputs(currency){ if(currency!=='KRW' && !Number(fxRates[currency])) return false; currencyInputs.forEach(input=>{ const won=getInputWon(input); const shown=KHGCurrency.convertFromKrw(won,currency,fxRates); input.value=KHGCurrency.formatInputAmount(shown,currency); input.step=currency==='KRW'?(input.dataset.krwStep||'1'):'1'; const ref=document.querySelector(`[data-currency-reference-for="${input.id}"]`); if(ref) ref.textContent=currency==='KRW'?'':`≈ ${KHGCurrency.formatWon(won,'en-US')}`; }); document.querySelectorAll('[data-currency-symbol]').forEach(el=>el.textContent=KHGCurrency.currencySymbol(currency)); activeInputCurrency=currency; return true; }
async function loadFx(){ currencySelect.disabled=true; try{ const r=await fetch('/api/fx'); const d=await r.json(); if(!r.ok) throw new Error(); fxRates=d.rates||{}; if(!renderCurrencyInputs(currencySelect.value)){ currencySelect.value='KRW'; renderCurrencyInputs('KRW'); } }catch(_){ fxRates={}; currencySelect.value='KRW'; renderCurrencyInputs('KRW'); } finally { currencySelect.disabled=false; } }
currencyInputs.forEach(input=>input.addEventListener('input',()=>syncCurrencyInput(input)));
currencySelect.addEventListener('change',()=>{ currencyInputs.forEach(syncCurrencyInput); if(!renderCurrencyInputs(currencySelect.value)) currencySelect.value=activeInputCurrency; });

const form=document.querySelector('#rentCheckForm'); const area=document.querySelector('#rentCheckArea'); const type=document.querySelector('#rentCheckType'); const deposit=document.querySelector('#rentCheckDeposit'); const rent=document.querySelector('#rentCheckRent'); const areaSqm=document.querySelector('#rentCheckAreaSqm'); const button=document.querySelector('#rentCheckButton'); const status=document.querySelector('#rentCheckStatus'); const result=document.querySelector('#rentCheckResult'); const rating=document.querySelector('#rentCheckRating'); const confidence=document.querySelector('#rentCheckConfidence'); const message=document.querySelector('#rentCheckMessage'); const meta=document.querySelector('#rentCheckMeta'); const asking=document.querySelector('#rentCheckAsking'); const median=document.querySelector('#rentCheckMedian'); const difference=document.querySelector('#rentCheckDifference'); const summary=document.querySelector('#rentCheckEvidenceSummary'); const body=document.querySelector('#rentCheckComparableBody'); const studioNote=document.querySelector('#rentCheckStudioNote');
function applyExplorerPrefill(){
  if(!window.KHGRentCheckPrefill) return;
  const prefill=KHGRentCheckPrefill.readRentCheckPrefill(location.search);
  if(prefill.lawdCd && [...area.options].some(option=>option.value===prefill.lawdCd)) area.value=prefill.lawdCd;
  if(prefill.type && [...type.options].some(option=>option.value===prefill.type)) type.value=prefill.type;
  if(Object.prototype.hasOwnProperty.call(prefill,'depositWon')) deposit.dataset.krwValue=String(Math.round(prefill.depositWon));
  if(Object.prototype.hasOwnProperty.call(prefill,'rentWon')) rent.dataset.krwValue=String(Math.round(prefill.rentWon));
  if(Object.prototype.hasOwnProperty.call(prefill,'areaSqm')) areaSqm.value=String(prefill.areaSqm);
}
function setStatus(text,state=''){ status.textContent=text; status.className=`rent-check-status${state?` ${state}`:''}`; }
function updateStudio(){ studioNote.hidden=type.value!=='studio'; }
function renderRows(items){ body.innerHTML=(items&&items.length)?items.map(item=>`<tr><td>${item.building||'-'}</td><td>${Number(item.areaSqm).toFixed(1)}㎡</td><td>${moneyHtml(item.depositWon)}</td><td>${moneyHtml(item.monthlyRentWon)}</td><td>${KHGDate.formatDate(item.contractDate, 'en-US')}</td></tr>`).join(''):'<tr class="empty-row"><td colspan="5">No reliable comparable set is available.</td></tr>'; }
function renderResult(data){ result.hidden=false; rating.textContent=KHGRentCheckUI.ratingLabel(data.rating); rating.className=`rent-rating ${data.rating||'insufficient'}`; message.textContent=KHGRentCheckUI.resultSentence(data); asking.innerHTML=moneyHtml(data.askingValueWon); median.innerHTML=data.medianValueWon==null?'-':moneyHtml(data.medianValueWon); difference.textContent=data.differencePct==null?'-':KHGRentCheckUI.formatDifference(data.differencePct); if(data.confidence){ confidence.hidden=false; confidence.textContent=KHGRentCheckUI.confidenceLabel(data.confidence); confidence.className=`confidence-pill ${data.confidence}`;}else confidence.hidden=true; const count=Number(data.comparableCount||0), months=Number(data.monthsUsed||12); meta.textContent=data.rating==='insufficient'?`Searched the latest ${months} completed months; not enough data for a reliable verdict.`:`${count} comparable contracts · latest ${months} completed months.`; summary.textContent=data.rating==='insufficient'?`${count} possible matches found; at least 3 suitable records are required.`:`${count} signed contracts matched the current comparison.`; renderRows(data.comparables||[]); }
form.addEventListener('submit',async e=>{ e.preventDefault(); syncCurrencyInput(deposit); syncCurrencyInput(rent); const depositWon=getInputWon(deposit), rentWon=getInputWon(rent), sqm=Number(areaSqm.value); if(!Number.isFinite(sqm)||sqm<=0) return setStatus('Size must be greater than zero.','error'); const mapped=KHGRentCheckUI.mapRentCheckType(type.value); setStatus('Finding similar official contracts…','loading'); button.disabled=true; try{ const q=new URLSearchParams({lawdCd:area.value,type:mapped.officialType,deposit:String(Math.round(depositWon)),rent:String(Math.round(rentWon)),area:String(sqm)}); const r=await fetch(`/api/rent-check?${q}`); const data=await r.json(); if(!r.ok) throw new Error(data.error||'Rent comparison failed.'); renderResult(data); setStatus(data.rating==='insufficient'?'Too few similar official contracts for a price verdict.':'Comparison complete.','success'); }catch(err){ result.hidden=true; setStatus(KHGRentCheckUI.humanizeRentCheckError(err.message),'error'); }finally{ button.disabled=false; } });
type.addEventListener('change',updateStudio); applyExplorerPrefill(); updateStudio(); loadFx();
