export {
  SINGAPORE_AREA_BASES,
  SINGAPORE_MARKET_SEGMENTS,
  SINGAPORE_PROPERTY_TYPES,
  SINGAPORE_SALE_TYPES,
  type SingaporeAreaBasis,
  type SingaporeMarketSegment,
  type SingaporePropertyType,
  type SingaporeSaleType,
} from './browser.ts';
export {
  readUraCredential,
  redactUraDiagnostic,
  type UraCredential,
} from './credential.ts';
export {
  SG_URA_PRIVATE_SALE_RIGHTS,
  type UraRightsDecision,
  type UraRightsOperation,
} from './rights.ts';
export {
  URA_DATA_URL,
  URA_PRIVATE_SALE_SERVICE,
  URA_TOKEN_URL,
  UraClientError,
  createUraClient,
  type UraClient,
  type UraClientErrorCode,
  type UraFetch,
} from './ura-client.ts';
export {
  parseUraPrivateSaleEnvelope,
  type UraPrivateSaleTransaction,
  type UraSourceOrder,
} from './ura-transaction.ts';
export {
  SINGAPORE_PUBLICATION_MINIMUM,
  SINGAPORE_SNAPSHOT_VERSION,
  assertSingaporePublicationRights,
  buildSingaporeProjectId,
  buildSingaporeSnapshot,
  calculatePsf,
  parseSingaporeSnapshot,
  stringifySingaporeSnapshot,
  toSquareFeet,
  type SingaporeProjectSummary,
  type SingaporePublicationRights,
  type SingaporePublishedSummary,
  type SingaporeSegmentSummary,
  type SingaporeSnapshot,
  type SingaporeSnapshotRecord,
} from './artifact.ts';
export {
  SINGAPORE_PUBLIC_INDEX_VERSION,
  buildSingaporePublicIndex,
  singaporeProjectPeriodKey,
  type PublicEvidenceReleaseRef,
  type SingaporePublicIndex,
} from './public-index.ts';
export {
  HDB_PUBLISHED_SNAPSHOT_VERSION,
  HDB_PUBLICATION_MINIMUM,
  HDB_SNAPSHOT_VERSION,
  HDB_SOURCE_DATASETS,
  buildHdbBlockId,
  buildHdbPublishedSnapshot,
  buildHdbSnapshot,
  parseHdbPropertyCsv,
  parseHdbPublishedSnapshot,
  parseHdbRentalCsv,
  parseHdbResaleCsv,
  parseHdbSnapshot,
  stringifyHdbSnapshot,
  stringifyHdbPublishedSnapshot,
  type HdbPropertyRecord,
  type HdbRentalRecord,
  type HdbResaleRecord,
  type HdbSnapshot,
} from './hdb.ts';
export type {
  HdbPublishedBlock,
  HdbPublishedDistribution,
  HdbPublishedSnapshot,
  HdbPublishedTown,
} from './hdb.ts';
export {
  SINGAPORE_CHECK_ARTIFACT_VERSION,
  SINGAPORE_CHECK_MARKETS,
  buildHdbRentCheckArtifact,
  buildHdbResaleCheckArtifact,
  buildSingaporeCheckArtifact,
  buildUraPrivateSaleCheckArtifact,
  parseSingaporeCheckArtifact,
  singaporeLatestCompletedMonth,
  stringifySingaporeCheckArtifact,
  type HdbRentCheckRecord,
  type HdbResaleCheckRecord,
  type SingaporeCheckArtifact,
  type SingaporeCheckMarket,
  type SingaporeCheckRecord,
  type UraPrivateSaleCheckRecord,
} from './check-artifact.ts';
export {
  SINGAPORE_CHECK_MAX_COMPLETED_MONTHS,
  SINGAPORE_CHECK_PUBLICATION_MINIMUM,
  compareSingaporeCheckOffers,
  evaluateSingaporeCheckOffer,
  singaporeCompletedMonthWindow,
  type HdbRentOffer,
  type HdbResaleOffer,
  type SingaporeAreaBand,
  type SingaporeCheckComparison,
  type SingaporeCheckMonthWindow,
  type SingaporeCheckOffer,
  type SingaporeCheckResult,
  type SingaporeCheckScopeLevel,
  type UraPrivateSaleOffer,
} from './check-engine.ts';
