export const BUYING_JOURNEY_COPY = {
  en: {
    changeCity: 'Change city', choose: 'Start with a city', hint: 'Choose a city to see its budgets and recorded-sale examples.',
    guide: 'Budget transactions', explore: 'Explore prices', budget: 'Purchase-price budget',
    budgetNote: 'Home price only. Taxes, fees and financing are separate.',
    viewGuide: 'Compare all budgets', results: 'What traded around this budget',
    evidence: 'See the transaction evidence', history: 'Historical sales · not available listings',
    scope: 'Three selected project groups. These are observed ranges, not all homes you could buy.',
    tokyoScope: 'One anonymous Chiyoda transaction at this checkpoint. Building names are not disclosed; this is not a typical or available home.',
    area: 'Recorded area', price: 'Recorded price', records: 'records in this price band', latest: 'Latest record',
    costs: 'Plan beyond the home price', costsNote: 'Start with this price budget, then adjust the price, purchase fees and ongoing costs.',
    costsAction: 'Open the cost scenario', feesAction: 'Read the buying-cost guide',
    offer: 'Already have a property in mind?', offerNote: 'Compare a proposed price with the relevant recorded evidence.',
    check: 'Check an offer', tokyoCheck: 'Compare Tokyo areas', tokyoCheckNote: 'Use neighbourhood records and cost tools. Anonymous sales cannot identify an individual building.',
    selected: 'Selected', original: 'Names follow source records.',
  },
  ko: {
    changeCity: '도시 바꾸기', choose: '어느 도시부터 볼까요?', hint: '도시를 고르면 예산별 실제 거래 사례를 볼 수 있어요.',
    guide: '예산별 실거래', explore: '실거래 탐색', budget: '매매가격 예산',
    budgetNote: '집값 기준입니다. 세금·수수료·금융 비용은 별도로 확인하세요.',
    viewGuide: '전체 예산 비교하기', results: '이 예산에서 거래된 집',
    evidence: '실제 거래 근거 보기', history: '과거 거래 사례 · 현재 매물이 아닙니다',
    scope: '선정된 단지 3곳의 거래 범위입니다. 이 예산으로 살 수 있는 모든 집을 뜻하지 않습니다.',
    tokyoScope: '해당 예산과 일치하는 지요다구의 익명 거래 1건입니다. 건물명은 공개되지 않으며 평균 주택이나 현재 매물을 뜻하지 않습니다.',
    area: '거래 면적', price: '거래가격', records: '건 · 해당 가격대', latest: '최근 거래',
    costs: '집값 다음의 비용까지', costsNote: '선택한 집값 예산에서 시작해 실제 가격과 취득·보유 비용을 조정하세요.',
    costsAction: '비용 계산기 열기', feesAction: '구매비용 가이드 읽기',
    offer: '이미 봐둔 집이 있나요?', offerNote: '제안받은 가격을 관련 실거래 자료와 비교해 보세요.',
    check: '제안받은 가격 확인', tokyoCheck: '도쿄 지역 비교', tokyoCheckNote: '지역별 거래와 비용 도구를 활용하세요. 익명 거래로 특정 건물을 확인할 수는 없습니다.',
    selected: '선택됨', original: '지역·건물명은 원자료 표기를 따릅니다.',
  },
  'zh-CN': {
    changeCity: '切换城市', choose: '从哪座城市开始？', hint: '选择城市，查看对应预算与真实成交案例。',
    guide: '预算成交比较', explore: '查看成交', budget: '房价预算',
    budgetNote: '仅为房价。税费、手续费与融资成本需单独考虑。',
    viewGuide: '在购房指南中比较', results: '这个预算附近的成交案例',
    evidence: '查看成交依据', history: '历史成交案例 · 并非在售房源',
    scope: '三个选定项目组的成交范围，并非该预算内全部可购住宅。',
    tokyoScope: '此预算点对应千代田区一笔匿名成交。原资料不公开楼名，不能代表平均住宅或在售房源。',
    area: '记录面积', price: '成交价格', records: '笔 · 此价格范围', latest: '最新记录',
    costs: '房价之外还需多少钱？', costsNote: '从所选房价预算开始，再调整实际价格、购置与持有费用。',
    costsAction: '打开费用计算器', feesAction: '阅读购房费用指南',
    offer: '已经看中一套房？', offerNote: '将收到的报价与相关成交资料进行比较。',
    check: '核对报价', tokyoCheck: '比较东京地区', tokyoCheckNote: '查看地区成交与费用工具。匿名成交无法确认具体楼宇。',
    selected: '已选择', original: '地区与项目名称沿用原始资料。',
  },
} as const;
