'use client';
import { useState,type FormEvent } from 'react';
import { questionCopy,errorCopy } from '@/lib/questions/copy';
import type { Member,SiteLocale } from '@/lib/questions/model';
import { api,ClientError } from './api';
import styles from './questions.module.css';
export function AccountPanel({locale,user,changed}:{locale:SiteLocale;user:Member|null;changed:()=>void}) {
 const c=questionCopy(locale); const [mode,setMode]=useState<'login'|'register'|'recover'>('login'); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [recovery,setRecovery]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>) {e.preventDefault();if(busy)return;const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));setBusy(true);setError('');try{const result=await api<{recovery?:string}>('/api/questions/account/',{...values,action:mode}); form.reset(); setRecovery(result.recovery??'');changed();}catch(e){setError(errorCopy(locale,e instanceof ClientError?e.code:'unavailable'));}finally{setBusy(false);}}
 async function logout(){setBusy(true);try{await api('/api/questions/account/',undefined,'DELETE');changed();}catch{setError(c.error);}finally{setBusy(false);}}
 return <section className={styles.account} aria-label={c.login}>{recovery&&<div className={styles.notice} role="status"><p>{c.recoverySave}</p><code className={styles.code}>{recovery}</code><button onClick={()=>setRecovery('')}>{c.savedCode}</button></div>}{user?<div className={styles.heading}><span>{c.signedIn}: <strong>{user.nickname}</strong></span><button disabled={busy} onClick={()=>void logout()}>{c.logout}</button></div>:<><p className={styles.muted}>{c.authHint}</p><div className={styles.actions}>{(['login','register','recover'] as const).map(m=><button key={m} disabled={busy} aria-pressed={m===mode} onClick={()=>{setMode(m);setError('');}}>{c[m]}</button>)}</div><form key={mode} className={styles.form} onSubmit={submit}><label>{c.username}<input name="username" autoComplete="username" required minLength={4} maxLength={24} pattern="[a-z0-9_]{4,24}" autoCapitalize="none" spellCheck={false}/><small>{c.usernameHint}</small></label>{mode==='register'&&<label>{c.nickname}<input name="nickname" autoComplete="nickname" required minLength={2} maxLength={30}/></label>}{mode==='recover'&&<label>{c.recovery}<input name="recovery" autoComplete="off" required minLength={48} maxLength={48}/></label>}<label>{c.password}<input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} required minLength={12} maxLength={128}/></label>{mode==='register'&&<p className={styles.muted}>{c.accountPrivacy}</p>}<button className={styles.primary} disabled={busy}>{c[mode]}</button></form></>}{error&&<p className={styles.error} role="alert">{error}</p>}</section>;
}
