'use client';
import { useState,type FormEvent } from 'react';
import Link from 'next/link';
import { cities,cityName,questionsHref,type QuestionPage,type QuestionPost } from '@/lib/questions/model';
import { api,ClientError,useRemote } from './api';
import styles from './questions.module.css';
export function AdminQuestions() {
 const [market,setMarket]=useState('');const [filter,setFilter]=useState('all');const [query,setQuery]=useState('');const [page,setPage]=useState(1);const [revision,setRevision]=useState(0);const [selected,setSelected]=useState<QuestionPost|null>(null);
 const params=new URLSearchParams({market,filter,q:query,page:String(page)}); const result=useRemote<QuestionPage>(`/api/internal/questions/?${params}`,revision);
 return <div className={styles.root}><p className={styles.muted}>일반 글은 기본 검사 후 공개됩니다. 링크·연락처 등 확인이 필요한 글과 신고를 검토하세요. 신고만으로 자동 삭제하지 않습니다.</p><form className={styles.filters} onSubmit={e=>{e.preventDefault();setQuery(String(new FormData(e.currentTarget).get('q')??''));setPage(1);}}><label>도시 <select value={market} onChange={e=>{setMarket(e.target.value);setPage(1);}}><option value="">전체</option>{cities.map(city=><option value={city} key={city}>{cityName(city,'ko')}</option>)}</select></label><label>상태 <select value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}>{[['all','전체'],['unanswered','답변 대기'],['pending','검토 대기'],['reported','신고 접수'],['hidden','숨긴 글']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><input name="q" aria-label="질문·단지·작성자 검색" placeholder="질문·단지·작성자 검색" maxLength={100}/><button>검색</button></form>
 {result.error?<p role="alert">{result.error==='unauthorized'?'관리자 로그인이 만료되었습니다. 다시 로그인하세요.':'질문을 불러오지 못했습니다.'}<button onClick={()=>setRevision(v=>v+1)}>다시 시도</button></p>:!result.data?<p role="status">불러오는 중…</p>:<><ul className={styles.list}>{result.data.posts.map(post=><li key={post.id}><button className={styles.postTitle} onClick={()=>setSelected(post)}>{post.title||post.body.slice(0,100)}</button><p className={styles.meta}>{cityName(post.market,'ko')} · {post.placeName||'지역 질문'} · {post.operator?'운영자':post.author} · {({published:'공개',pending:'검토 대기',hidden:'숨김',deleted:'삭제'} as Record<string,string>)[post.status]}{post.reports?` · 미처리 신고 ${post.reports}건`:''}{post.blocked?' · 작성 제한':''}</p></li>)}</ul>{!result.data.posts.length&&<p>조건에 맞는 글이 없습니다.</p>}<div className={styles.pager}><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>이전</button><span>{page}</span><button disabled={!result.data.hasMore} onClick={()=>setPage(p=>p+1)}>다음</button></div></>}
 {selected&&<AdminDetail key={selected.id} post={selected} revision={revision} close={()=>setSelected(null)} changed={()=>setRevision(v=>v+1)}/>}
 </div>;
}
function AdminDetail({post,revision,close,changed}:{post:QuestionPost;revision:number;close:()=>void;changed:()=>void}) {
 const data=useRemote<QuestionPage>(`/api/internal/questions/?id=${post.id}`,revision);const current=data.data?.question??post;const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));setBusy(true);setError('');setMessage('');try{await api('/api/internal/questions/',{...values,id:post.id,parentId:current.parentId??current.id,locale:'ko'});form.reset();setMessage('처리 내용과 이력을 저장했습니다.');changed();}catch(e){setError(e instanceof ClientError&&e.code==='unauthorized'?'로그인이 만료되었습니다.':'처리하지 못했습니다. 입력값과 글 상태를 확인해 주세요.');}finally{setBusy(false);}}
 return <section className={styles.notice} aria-label="질문 상세 관리"><div className={styles.heading}><h2>{current.title||'답변 관리'}</h2><button onClick={close}>닫기</button></div><p className={styles.body}>{current.body}</p><p>{current.author} · {current.reason&&`검토 사유: ${current.reason}`}</p><Link href={questionsHref('ko',current.market,current.parentId??current.id)} target="_blank">공개 화면 열기</Link>{error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status">{message}</p>}
 <form className={styles.form} onSubmit={submit}><label>처리<select name="action"><option value="hide">글 숨기기</option><option value="publish">공개·복구</option><option value="resolve">신고 검토 완료</option>{current.userId&&<option value={current.blocked?'unblock':'block'}>{current.blocked?'작성 제한 해제':'작성자 제한 (기존 글은 유지)'}</option>}</select></label><label>처리 이유<textarea name="reason" required minLength={3} maxLength={500}/></label><button disabled={busy} className={styles.primary}>처리 저장</button></form>
 {current.status==='published'&&<form className={styles.form} onSubmit={submit}><input type="hidden" name="action" value="reply"/><label>운영자 답변<textarea name="body" required minLength={5} maxLength={4000}/></label><button disabled={busy}>운영자 답변 등록</button></form>}
 <h3>신고 내용</h3>{data.data?.reports?.map((report,index)=><p key={index}>{report.reason} · {report.resolved_at?'처리 완료':'미처리'}</p>)}<h3>처리 이력 (최근 50건)</h3>{data.error&&<p role="alert">이력을 불러오지 못했습니다.</p>}<ul>{data.data?.events?.map((event,index)=><li key={index}>{new Date(event.created_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} · {event.actor} · {({created:'등록',edited:'작성자 수정',published:'공개',hidden:'숨김',deleted:'작성자 삭제',reports_resolved:'신고 처리',block:'작성 제한',unblock:'작성 제한 해제'} as Record<string,string>)[event.action]??event.action} · {event.reason}</li>)}</ul></section>;
}
