'use client';
import Link from 'next/link';
import { useState,type FormEvent } from 'react';
import { cities,cityName,prefix,questionsHref,type City,type Scope,type SiteLocale,type Member,type QuestionPage,type QuestionPost } from '@/lib/questions/model';
import { questionCopy,errorCopy } from '@/lib/questions/copy';
import { AccountPanel } from './account-panel';
import { PostActions } from './post-actions';
import { api,ClientError,useRemote } from './api';
import styles from './questions.module.css';
export function QuestionsClient({locale,initialMarket='',scope,token,questionId,compact=false}:{locale:SiteLocale;initialMarket?:City|'';scope?:Scope;token?:string;questionId?:string;compact?:boolean}) {
 const c=questionCopy(locale);const [market,setMarket]=useState<City|''>(scope?.market??initialMarket);const [page,setPage]=useState(1);const [query,setQuery]=useState('');const [mine,setMine]=useState(false);const [revision,setRevision]=useState(0);const [composer,setComposer]=useState(false);const [account,setAccount]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const changed=()=>setRevision(v=>v+1);const identity=useRemote<{user:Member|null}>('/api/questions/account/',revision);const user=identity.data?.user??null;
 const params=new URLSearchParams({market,q:query,page:String(page),...(scope?{place:scope.path}:{}),...(questionId?{id:questionId}:{}),...(mine?{mine:'1'}:{})});
 const result=useRemote<QuestionPage>(`/api/questions/?${params}`,revision);const data=result.data;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));if(!user){setAccount(true);setError(c.requiredLogin);return;}setBusy(true);setError('');setMessage('');try{const r=await api<{id:string;status:string}>('/api/questions/',{...values,action:'create',market:scope?.market??values.market??market,scopeToken:token,parentId:questionId,locale});form.reset();setMessage(r.status==='pending'?c.held:c.published);changed();setComposer(false);}catch(e){const code=e instanceof ClientError?e.code:'unavailable';setError(errorCopy(locale,code));if(code==='login_required'){setAccount(true);changed();}}finally{setBusy(false);}}
 function meta(post:QuestionPost){return <div className={styles.meta}><span>{post.operator?c.operator:post.author}</span>{post.operator&&<span className={styles.badge}>{c.operator}</span>}<time dateTime={post.createdAt}>{new Intl.DateTimeFormat(locale==='zh-CN'?'zh-CN':locale,{dateStyle:'medium',timeZone:'UTC'}).format(new Date(post.createdAt))}</time>{post.status==='pending'&&<span className={styles.badge}>{c.pending}</span>}</div>;}
 return <div className={`${styles.root} ${compact?styles.compact:styles.page}`} data-questions={compact?'place':'feed'}>
 {compact?<div className={styles.heading}><h2>{c.placeHeading}</h2><button className={styles.primary} onClick={()=>{setComposer(!composer);setAccount(true);}}>{c.ask}</button></div>:<><div className={styles.heading}><div><h1>{questionId?(data?.question?.title??c.heading):c.heading}</h1>{!questionId&&<p className={styles.muted}>{c.intro}</p>}</div><button onClick={()=>setAccount(!account)}>{user?user.nickname:c.login}</button></div>{questionId?<Link href={questionsHref(locale,data?.question?.market)}>{c.back}</Link>:<div className={styles.filters}>{(['',...cities] as const).map(city=><button key={city} aria-pressed={market===city} onClick={()=>{setMarket(city);setPage(1);}}>{city?cityName(city,locale):c.all}</button>)}<form className={styles.search} onSubmit={e=>{e.preventDefault();setQuery(String(new FormData(e.currentTarget).get('q')??''));setPage(1);}}><input name="q" aria-label={c.search} placeholder={c.search} maxLength={100}/><button>{c.searchButton}</button></form><button className={styles.primary} onClick={()=>{setComposer(!composer);if(!user)setAccount(true);}}>{c.ask}</button>{user&&<button aria-pressed={mine} onClick={()=>{setMine(!mine);setPage(1);}}>{c.mine}</button>}</div>}</>}
 {account&&<AccountPanel locale={locale} user={user} changed={()=>{setMine(false);changed();}}/>}
 {result.error?<div role="alert" className={styles.error}><p>{result.error==='not_found'?c.notFound:errorCopy(locale,result.error)}</p><button onClick={changed}>{c.retry}</button></div>:!data?<p role="status" className={styles.muted}>{c.loading}</p>:<>
 {data.question&&<article className={styles.post}>{data.question.placePath&&<Link href={`${prefix(locale)}${data.question.placePath}`}>{data.question.placeName} · {c.returnPlace}</Link>}{meta(data.question)}<p className={styles.body}>{data.question.body}</p>{user&&<PostActions post={data.question} locale={locale} changed={deleted=>{if(deleted)window.location.assign(questionsHref(locale,data.question!.market));else changed();}}/>}</article>}
 {!data.posts.length&&!composer&&<p className={styles.muted}>{questionId?c.noAnswers:c.empty}</p>}
 <ul className={styles.list}>{(compact?data.posts.slice(0,3):data.posts).map(post=><li key={post.id}>{!questionId?<><span className={styles.muted}>{post.placeName||cityName(post.market,locale)}</span><Link className={styles.postTitle} href={questionsHref(locale,post.market,post.id)}>{post.title}</Link>{meta(post)}<span className={styles.muted}>{c.count} {post.answers}</span></>:<>{meta(post)}<p className={styles.body}>{post.body}</p>{user&&<PostActions post={post} locale={locale} changed={()=>changed()}/>}</>}</li>)}</ul>
 {!compact&&(page>1||data.hasMore)&&<div className={styles.pager}><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>{c.previous}</button><span>{page}</span><button disabled={!data.hasMore} onClick={()=>setPage(p=>p+1)}>{c.next}</button></div>}
 </>}
 {(composer||(questionId&&data?.question?.status==='published'))&&<form className={styles.form} onSubmit={submit} aria-label={questionId?c.answer:c.ask}>{!questionId&&<>{scope?<p>{cityName(scope.market,locale)} · {scope.name}</p>:<label>{c.market}<select name="market" required defaultValue={market||'seoul'}>{cities.map(city=><option key={city} value={city}>{cityName(city,locale)}</option>)}</select></label>}<label>{c.title}<input name="title" required minLength={5} maxLength={160}/></label></>}<label>{questionId?c.answer:c.body}<textarea name="body" required minLength={5} maxLength={4000}/></label><p className={styles.muted}>{c.rules}</p>{!user&&<p>{c.requiredLogin} <button type="button" onClick={()=>setAccount(true)}>{c.login}</button></p>}<div className={styles.actions}><button className={styles.primary} disabled={busy}>{questionId?c.send:c.submit}</button>{composer&&<button type="button" onClick={()=>setComposer(false)}>{c.cancel}</button>}</div></form>}
 {error&&<p role="alert" className={styles.error}>{error}</p>}{message&&<p role="status" className={styles.success}>{message}</p>}
 {compact&&<Link href={questionsHref(locale,scope?.market??(market||undefined))}>{c.cityQuestions} →</Link>}
 </div>;
}
