export type TokyoLocale = 'en' | 'ko' | 'zh-CN';
const copy: Record<string, [string, string]> = {
  'Chiyoda':['지요다구','千代田区'], 'Chuo':['주오구','中央区'], 'Minato':['미나토구','港区'],
  'Shinjuku':['신주쿠구','新宿区'], 'Bunkyo':['분쿄구','文京区'], 'Taito':['다이토구','台东区'],
  'Sumida':['스미다구','墨田区'], 'Koto':['고토구','江东区'], 'Shinagawa':['시나가와구','品川区'],
  'Meguro':['메구로구','目黑区'], 'Ota':['오타구','大田区'], 'Setagaya':['세타가야구','世田谷区'],
  'Shibuya':['시부야구','涩谷区'], 'Nakano':['나카노구','中野区'], 'Suginami':['스기나미구','杉并区'],
  'Toshima':['도시마구','丰岛区'], 'Kita':['기타구','北区'], 'Arakawa':['아라카와구','荒川区'],
  'Itabashi':['이타바시구','板桥区'], 'Nerima':['네리마구','练马区'], 'Adachi':['아다치구','足立区'],
  'Katsushika':['가쓰시카구','葛饰区'], 'Edogawa':['에도가와구','江户川区'],
  'Some filters are invalid. Choose a ward, year and quarter below.':['일부 조건이 올바르지 않습니다. 구·연도·분기를 다시 선택하세요.','部分筛选无效，请重新选择区、年份和季度。'],
  'Published records are temporarily unavailable. Please try again shortly.':['공개 거래 자료를 불러오지 못했습니다. 잠시 후 다시 시도하세요.','公开成交资料暂不可用，请稍后重试。'],
  'These are completed transactions reported by area, not homes currently for sale. The source does not disclose building names, exact addresses or unit identities.':['지역 단위로 신고된 완료 거래이며 현재 판매 중인 매물이 아닙니다. 원자료는 건물명·정확한 주소·호실을 공개하지 않습니다.','这是按地区申报的已完成成交，并非在售房源。原始资料不公开楼盘名称、精确地址或单元身份。'],
  'Dates are reported by quarter. Prices and areas use the precision supplied by MLIT. Homes with an area range are left out when you set a minimum or maximum area; similar-looking records can be separate transactions.':['거래 시점은 분기로 표시하며 가격·면적은 국토교통성 원자료의 정밀도를 따릅니다. 면적 필터를 쓰면 정확한 숫자 면적이 없는 기록은 제외합니다. 비슷해 보이는 기록도 별개의 거래일 수 있습니다.','日期按季度报告，价格和面积沿用MLIT提供的精度。设置面积上下限时会排除仅提供面积范围的记录；相似记录也可能属于不同成交。'],
  'Property type and area filters apply. Other wards use their latest available quarter when this period is missing. Neighbourhoods show the selected ward and quarter. Area medians are not like-for-like home valuations.':['주택 유형·면적 조건이 적용됩니다. 다른 구는 해당 분기 자료가 없으면 최신 공개 분기를 사용하며, 동네는 선택한 구·분기를 표시합니다. 지역 중앙값은 개별 주택의 감정가격이 아닙니다.','应用房产类型和面积筛选。其他区在缺少所选季度时使用最新可用季度。街区显示所选区及季度。地区中位价并非同等条件住宅估价。'],
  'Ward reference points: MLIT 2020':['구 기준 좌표: 국토교통성 2020','区参考坐标：MLIT 2020'],
  'Derived by SignedPrice. Neighbourhoods are selected from published transaction records, without inferred building locations.':['SignedPrice가 가공했습니다. 공개 거래 자료의 동네를 사용하며 건물 위치를 추정하지 않습니다.','由SignedPrice加工。街区取自公开成交记录，不推断楼盘位置。'],
  'Tokyo stories & insights':['도쿄 이야기·인사이트','东京故事与洞察'],
  'Transaction price information, edited by SignedPrice.':['SignedPrice가 가공한 부동산 거래가격 정보.','由SignedPrice编辑的房地产成交价格资料。'],
  'MLIT Real Estate Information Library':['일본 국토교통성 부동산 정보 라이브러리','日本国土交通省不动产信息库'],
  'Source':['출처','来源'], 'Source retrieved':['원자료 수집일','原始资料获取日期'],
  'Page':['페이지','页'], 'of':['/','/'], 'View':['보기','查看'],
  'Find your Tokyo neighbourhood':['도쿄 동네 가이드 보기','查看东京街区指南'],
  'Names in transaction records follow the original source.':['거래 기록의 동네명은 원자료 표기를 따릅니다.','成交记录中的街区名沿用原始资料名称。'],
  'transactions': ['건의 거래', '笔成交'],
  'Change property type in More filters.': ['추가 필터에서 주택 유형을 변경할 수 있어요.', '可在更多筛选中更改房产类型。'],
  'of 23 wards available': ['/ 23개 구 공개', '/ 23区已有数据'],
  'Transactions are unavailable': ['거래 자료를 불러올 수 없습니다', '成交数据暂不可用'],
  'Prices for this period are not available yet.': ['이 기간의 거래 자료가 아직 없습니다.', '此期间的成交数据尚未发布。'],
  'We have not published records for this ward and quarter. This does not mean that no homes traded.': ['이 구·분기의 자료가 아직 공개되지 않았습니다. 거래가 없었다는 뜻은 아닙니다.', '本区本季度的数据尚未发布，不代表没有住房成交。'],
  'Price, high to low · Area-level records; building names are not disclosed.': ['가격 높은 순 · 지역 단위 자료이며 건물명은 공개되지 않습니다.', '价格由高到低 · 区域级成交记录，不公开楼盘名称。'],
  'Area not disclosed': ['면적 미공개', '面积未公开'], 'Layout not disclosed': ['평면 미공개', '户型未公开'],
  'Built': ['준공', '建造年份'], 'not disclosed': ['미공개', '未公开'], 'Structure not disclosed': ['구조 미공개', '结构未公开'],
  'No published records match these filters. Try a wider area range or another neighbourhood.': ['조건에 맞는 거래가 없습니다. 면적 범위를 넓히거나 다른 동네를 선택하세요.', '没有符合筛选条件的成交记录，请扩大面积范围或选择其他街区。'],
  'Preparing Tokyo ward map…': ['도쿄 지도를 준비하는 중…', '正在加载东京地图…'],
  'Neighbourhood summaries are temporarily unavailable. You can still search the transaction records.': ['동네 요약을 일시적으로 불러올 수 없습니다. 거래 내역은 검색할 수 있습니다.', '街区汇总暂不可用，您仍可搜索成交记录。'],
  'No neighbourhoods match this period and property filters. Try another quarter or a wider area range.': ['조건에 맞는 동네 자료가 없습니다. 다른 분기나 넓은 면적 범위를 선택하세요.', '没有符合该期间及房产筛选条件的街区，请选择其他季度或扩大面积范围。'],
  'Tokyo': ['도쿄', '东京'], 'Explore': ['실거래가 탐색', '探索成交价'], 'Overview': ['시장 개요', '市场概览'],
  'Data source': ['데이터 출처', '数据来源'], 'Market overview': ['시장 개요', '市场概览'],
  'Choose a ward, then a neighbourhood to compare recorded home prices.': ['구와 동네를 선택해 주택 실거래가를 비교하세요.', '选择区和街区，比较住房成交价格。'],
  'Apartments & condominiums': ['아파트·공동주택', '公寓住宅'], 'All property types': ['모든 부동산 유형', '所有房产类型'],
  'Neighbourhood, layout or built year': ['동네·평면·준공연도', '街区、户型或建造年份'], 'Ward': ['구', '区'],
  'Explore transactions': ['실거래가 보기', '查看成交记录'], 'More filters': ['추가 필터', '更多筛选'],
  'Period, property type and area': ['기간·주택 유형·면적', '时间、房产类型和面积'], 'Property type': ['부동산 유형', '房产类型'],
  'Land with a building': ['건물이 있는 토지', '土地及建筑物'], 'Land only': ['토지', '土地'],
  'Min area (m²)': ['최소 면적 (㎡)', '最小面积 (㎡)'], 'Max area (m²)': ['최대 면적 (㎡)', '最大面积 (㎡)'],
  'Latest available period for this ward': ['이 구의 최신 공개 기간', '本区最新公开季度'], 'Year': ['연도', '年份'], 'Quarter': ['분기', '季度'],
  'Browse published wards': ['공개 자료가 있는 구 보기', '查看已有数据的区'], 'recorded transactions': ['건의 실거래', '笔成交记录'],
  'Explore Tokyo by area': ['도쿄 지역별 탐색', '按区域探索东京'], 'Ward → neighbourhood → recorded home prices': ['구 → 동네 → 주택 실거래가', '区 → 街区 → 住房成交价'],
  'Change ward · 23 wards': ['구 변경 · 23개 구', '切换区域 · 23区'], 'Find a ward': ['구 검색', '搜索区'],
  'View coverage': ['수집 범위 보기', '查看数据覆盖'], 'No wards match this search.': ['검색 결과가 없습니다.', '没有匹配的区。'],
  'Median recorded price': ['실거래가 중앙값', '成交价中位数'], 'Loading area transactions…': ['지역 거래를 불러오는 중…', '正在加载区域成交记录…'],
  'Choose an area to see its recorded home prices.': ['동네를 선택해 주택 실거래가를 확인하세요.', '选择街区查看住房成交价。'],
  'Find a neighbourhood': ['동네 검색', '搜索街区'], 'Neighbourhood · transactions': ['동네 · 거래 건수', '街区 · 成交笔数'], 'Median price': ['가격 중앙값', '价格中位数'],
  'Map coverage and source': ['지도 범위·출처', '地图范围与来源'], 'Record details': ['거래 상세', '成交详情'],
  'Previous': ['이전', '上一页'], 'Next': ['다음', '下一页'], 'About these recorded prices': ['실거래 자료 안내', '关于成交数据'],
};
export function tokyoText(locale: TokyoLocale, text: string): string { return locale === 'en' ? text : copy[text]?.[locale === 'ko' ? 0 : 1] ?? text; }
export function tokyoHref(locale: TokyoLocale, href: string): string { return locale === 'en' || !href.startsWith('/jp/tokyo') ? href : `/${locale === 'zh-CN' ? 'zh-cn' : locale}${href}`; }
