export type TokyoLocale = 'en' | 'ko' | 'zh-CN';
const copy: Record<string, [string, string]> = {
  'transactions': ['건의 거래', '笔成交'],
  'Change property type in More filters.': ['추가 필터에서 주택 유형을 변경할 수 있어요.', '可在更多筛选中更改房产类型。'],
  'of 23 wards available': ['/ 23개 구 공개', '/ 23区已有数据'],
  'Transactions are unavailable': ['거래 자료를 불러올 수 없습니다', '成交数据暂不可用'],
  'Prices for this period are not available yet.': ['이 기간의 거래 자료가 아직 없습니다.', '此期间的成交数据尚未发布。'],
  'We have not published records for this ward and quarter. This does not mean that no homes traded.': ['이 구·분기의 자료가 아직 공개되지 않았습니다. 거래가 없었다는 뜻은 아닙니다.', '本区本季度的数据尚未发布，不代表没有住房成交。'],
  'Price, high to low · Area-level records; building names are not disclosed.': ['가격 높은 순 · 지역 단위 자료이며 건물명은 공개되지 않습니다.', '价格由高到低 · 区域级成交记录，不公开楼盘名称。'],
  'Area not disclosed': ['면적 미공개', '面积未公开'], 'Layout not disclosed': ['평면 미공개', '户型未公开'],
  'Built': ['준공', '建造年份'], 'not disclosed': ['미공개', '未公开'], 'Structure not disclosed': ['구조 미공개', '结构未公开'],
  'No published records match these filters. Try a wider area range or another neighbourhood.': ['조건에 맞는 거래가 없습니다. 면적 범위를 넓히거나 다른 동네를 선택하세요.', '没有符合筛选条件的成交记录，请扩大面积范围或选择其他街区。'],
  'Preparing Tokyo ward map…': ['도쿄 지도를 준비하는 중…', '正在加载东京地图…'],
  'Neighbourhood summaries are temporarily unavailable. You can still search the transaction records.': ['동네 요약을 일시적으로 불러올 수 없습니다. 거래 내역은 검색할 수 있습니다.', '街区汇总暂不可用，您仍可搜索成交记录。'],
  'No neighbourhoods match this period and property filters. Try another quarter or a wider area range.': ['조건에 맞는 동네 자료가 없습니다. 다른 분기나 넓은 면적 범위를 선택하세요.', '没有符合该期间及房产筛选条件的街区，请选择其他季度或扩大面积范围。'],
  'Tokyo': ['도쿄', '东京'], 'Explore': ['실거래가 탐색', '探索成交价'], 'Overview': ['시장 개요', '市场概览'],
  'Data source': ['데이터 출처', '数据来源'], 'Market overview': ['시장 개요', '市场概览'],
  'Choose a ward, then a neighbourhood to compare recorded home prices.': ['구와 동네를 선택해 주택 실거래가를 비교하세요.', '选择区和街区，比较住房成交价格。'],
  'Apartments & condominiums': ['아파트·공동주택', '公寓住宅'], 'All property types': ['모든 부동산 유형', '所有房产类型'],
  'Neighbourhood, layout or built year': ['동네·평면·준공연도', '街区、户型或建造年份'], 'Ward': ['구', '区'],
  'Explore transactions': ['실거래가 보기', '查看成交记录'], 'More filters': ['추가 필터', '更多筛选'],
  'Period, property type and area': ['기간·주택 유형·면적', '时间、房产类型和面积'], 'Property type': ['부동산 유형', '房产类型'],
  'Land with a building': ['건물이 있는 토지', '土地及建筑物'], 'Land only': ['토지', '土地'],
  'Min area (m²)': ['최소 면적 (㎡)', '最小面积 (㎡)'], 'Max area (m²)': ['최대 면적 (㎡)', '最大面积 (㎡)'],
  'Latest available period for this ward': ['이 구의 최신 공개 기간', '本区最新公开季度'], 'Year': ['연도', '年份'], 'Quarter': ['분기', '季度'],
  'Browse published wards': ['공개 자료가 있는 구 보기', '查看已有数据的区'], 'recorded transactions': ['건의 실거래', '笔成交记录'],
  'Explore Tokyo by area': ['도쿄 지역별 탐색', '按区域探索东京'], 'Ward → neighbourhood → recorded home prices': ['구 → 동네 → 주택 실거래가', '区 → 街区 → 住房成交价'],
  'Change ward · 23 wards': ['구 변경 · 23개 구', '切换区域 · 23区'], 'Find a ward': ['구 검색', '搜索区'],
  'View coverage': ['수집 범위 보기', '查看数据覆盖'], 'No wards match this search.': ['검색 결과가 없습니다.', '没有匹配的区。'],
  'Median recorded price': ['실거래가 중앙값', '成交价中位数'], 'Loading area transactions…': ['지역 거래를 불러오는 중…', '正在加载区域成交记录…'],
  'Choose an area to see its recorded home prices.': ['동네를 선택해 주택 실거래가를 확인하세요.', '选择街区查看住房成交价。'],
  'Find a neighbourhood': ['동네 검색', '搜索街区'], 'Neighbourhood · transactions': ['동네 · 거래 건수', '街区 · 成交笔数'], 'Median price': ['가격 중앙값', '价格中位数'],
  'Map coverage and source': ['지도 범위·출처', '地图范围与来源'], 'Record details': ['거래 상세', '成交详情'],
  'Previous': ['이전', '上一页'], 'Next': ['다음', '下一页'], 'About these recorded prices': ['실거래 자료 안내', '关于成交数据'],
};
export function tokyoText(locale: TokyoLocale, text: string): string { return locale === 'en' ? text : copy[text]?.[locale === 'ko' ? 0 : 1] ?? text; }
export function tokyoHref(locale: TokyoLocale, href: string): string { return locale === 'en' || !href.startsWith('/jp/tokyo') ? href : `/${locale === 'zh-CN' ? 'zh-cn' : locale}${href}`; }
