(function(){
'use strict';
const language = document.documentElement.lang === 'zh-CN' ? 'zh-CN' : 'en';
const locale = language === 'zh-CN' ? 'zh-CN' : 'en-US';
const zh = language === 'zh-CN';
const currencySelect=document.querySelector('#currencySelect');
const currencyInputs=[...document.querySelectorAll('[data-currency-input]')];
let fxRates={}; let activeInputCurrency='KRW';
function selectedCurrency(){return currencySelect?currencySelect.value:'KRW';}
function getInputWon(input){if(!input||!input.dataset||!Object.prototype.hasOwnProperty.call(input.dataset,'krwValue'))return null;const n=Number(input.dataset.krwValue);return Number.isFinite(n)&&n>=0?n:null;}
function renderCurrencyReference(input,won,currency){const ref=document.querySelector(`[data-currency-reference-for="${input.id}"]`);if(ref)ref.textContent=currency==='KRW'?KHGCurrency.manwonLabel(won,language):`≈ ${KHGCurrency.formatWon(won,locale)}`;}
function syncCurrencyInput(input){if(!input)return false;const amount=KHGCurrency.parseInputAmount(input.value);const won=KHGCurrency.convertToKrw(amount,activeInputCurrency,fxRates);if(won==null||won<0){delete input.dataset.krwValue;const ref=document.querySelector(`[data-currency-reference-for="${input.id}"]`);if(ref)ref.textContent='';if(typeof input.setAttribute==='function')input.setAttribute('aria-invalid','true');return false;}input.dataset.krwValue=String(Math.round(won));renderCurrencyReference(input,won,activeInputCurrency);if(typeof input.removeAttribute==='function')input.removeAttribute('aria-invalid');return true;}
function moneyHtml(won){return KHGCurrency.formatMoneyHtml(won,selectedCurrency(),fxRates,locale);}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function renderCurrencyInputs(currency){if(currency!=='KRW'&&!Number(fxRates[currency]))return false;const values=currencyInputs.map(input=>({input,won:getInputWon(input)}));if(values.some(item=>item.won==null))return false;values.forEach(({input,won})=>{const shown=KHGCurrency.convertFromKrw(won,currency,fxRates);input.value=KHGCurrency.formatInputAmount(shown,currency,locale);renderCurrencyReference(input,won,currency);});document.querySelectorAll('[data-currency-symbol]').forEach(el=>el.textContent=KHGCurrency.currencySymbol(currency));document.querySelectorAll('[data-currency-code]').forEach(el=>el.textContent=currency);activeInputCurrency=currency;return true;}
async function loadFx(){if(!currencySelect)return;currencySelect.disabled=true;try{const r=await fetch('/api/fx');const d=await r.json();if(!r.ok)throw new Error();fxRates=d.rates||{};if(!renderCurrencyInputs(currencySelect.value)){currencySelect.value=activeInputCurrency;renderCurrencyInputs(activeInputCurrency);}}catch(_){fxRates={};currencySelect.value='KRW';renderCurrencyInputs('KRW');}finally{currencySelect.disabled=false;}}
currencyInputs.forEach(input=>input.addEventListener('input',()=>{const amount=KHGCurrency.parseInputAmount(input.value);if(amount!=null)input.value=KHGCurrency.formatInputAmount(amount,activeInputCurrency,locale);syncCurrencyInput(input);}));
if(currencySelect)currencySelect.addEventListener('change',()=>{const valid=currencyInputs.every(syncCurrencyInput);if(!valid||!renderCurrencyInputs(currencySelect.value))currencySelect.value=activeInputCurrency;});

const form=document.querySelector('#rentCheckForm');
const area=document.querySelector('#rentCheckArea');
const type=document.querySelector('#rentCheckType');
const deposit=document.querySelector('#rentCheckDeposit');
const rent=document.querySelector('#rentCheckRent');
const areaSqm=document.querySelector('#rentCheckAreaSqm');
const sizeController=window.KHGRentSize?KHGRentSize.init(document):null;
const button=document.querySelector('#rentCheckButton');
const status=document.querySelector('#rentCheckStatus');
const result=document.querySelector('#rentCheckResult');
const rating=document.querySelector('#rentCheckRating');
const confidence=document.querySelector('#rentCheckConfidence');
function ensureResultFeedback(){let confidenceDetails=document.querySelector('#rentCheckConfidenceDetails');if(!confidenceDetails){confidenceDetails=document.createElement('details');confidenceDetails.id='rentCheckConfidenceDetails';confidenceDetails.className='rent-check-confidence-details';confidenceDetails.hidden=true;confidenceDetails.innerHTML='<summary></summary><p id="rentCheckConfidenceExplanation"></p>';result.querySelector('.rent-check-verdict').appendChild(confidenceDetails);}const confidenceSummary=confidenceDetails.querySelector('summary');if(confidenceSummary)confidenceSummary.textContent=zh?'为什么是这个样本等级？':'Why this evidence level?';let nextStep=document.querySelector('#rentCheckNextStep');if(!nextStep){nextStep=document.createElement('section');nextStep.id='rentCheckNextStep';nextStep.className='rent-check-next-step';nextStep.hidden=true;nextStep.innerHTML=`<span class="eyebrow">${zh?'下一步':'NEXT STEP'}</span><h3 id="rentCheckNextHeading"></h3><p id="rentCheckNextBody"></p><div class="rent-check-next-actions"><a id="rentCheckNextPrimary" class="search-button" href="#"></a></div>`;}const savedMount=result.querySelector('[data-saved-quote-mount]');if(savedMount)savedMount.insertAdjacentElement('beforebegin',nextStep);else result.appendChild(nextStep);return{confidenceDetails,confidenceSummary,confidenceExplanation:confidenceDetails.querySelector('#rentCheckConfidenceExplanation'),nextStep,nextHeading:nextStep.querySelector('#rentCheckNextHeading'),nextBody:nextStep.querySelector('#rentCheckNextBody'),nextPrimary:nextStep.querySelector('#rentCheckNextPrimary')};}
function ensureVerdictPresentation(){const container=result.querySelector('.rent-check-verdict');let primary=container.querySelector('[data-rent-verdict-primary]');if(!primary){primary=document.createElement('div');primary.className='rent-check-verdict-primary';primary.dataset.rentVerdictPrimary='true';primary.innerHTML='<span data-rent-verdict-icon aria-hidden="true"></span><strong data-rent-verdict-label></strong><p data-rent-verdict-difference></p><span data-rent-verdict-comparison></span><p data-rent-verdict-annualized></p><p data-rent-verdict-sample></p>';container.insertAdjacentElement('afterbegin',primary);}const resultSummary=container.parentElement;if(resultSummary){let basis=resultSummary.querySelector('.rent-check-basis');if(!basis){basis=document.createElement('div');basis.className='rent-check-basis';resultSummary.appendChild(basis);}const metaElement=document.querySelector('#rentCheckMeta');const detailsElement=document.querySelector('#rentCheckConfidenceDetails');if(metaElement)basis.appendChild(metaElement);if(detailsElement)basis.appendChild(detailsElement);}return{primary,icon:primary.querySelector('[data-rent-verdict-icon]'),label:primary.querySelector('[data-rent-verdict-label]'),difference:primary.querySelector('[data-rent-verdict-difference]'),comparison:primary.querySelector('[data-rent-verdict-comparison]'),annualized:primary.querySelector('[data-rent-verdict-annualized]'),sample:primary.querySelector('[data-rent-verdict-sample]')};}
const feedback=ensureResultFeedback();
const verdictFeedback=ensureVerdictPresentation();
const confidenceDetails=feedback.confidenceDetails;
const confidenceSummary=feedback.confidenceSummary;
const confidenceExplanation=feedback.confidenceExplanation;
const message=document.querySelector('#rentCheckMessage');
const meta=document.querySelector('#rentCheckMeta');
const asking=document.querySelector('#rentCheckAsking');
const median=document.querySelector('#rentCheckMedian');
const difference=document.querySelector('#rentCheckDifference');
const summary=document.querySelector('#rentCheckEvidenceSummary');
const body=document.querySelector('#rentCheckComparableBody');
function ensureComparablesToggle(){let toggle=document.querySelector('#rentCheckComparablesToggle');if(!toggle){toggle=document.createElement('button');toggle.id='rentCheckComparablesToggle';toggle.className='rent-check-comparables-toggle';toggle.type='button';toggle.hidden=true;toggle.setAttribute('aria-controls','rentCheckComparableBody');result.querySelector('.table-wrap').insertAdjacentElement('afterend',toggle);}return toggle;}
const comparablesToggle=ensureComparablesToggle();
const evidenceDisclosure=typeof KHGRentCheckUI.mountEvidenceDisclosure==='function'?KHGRentCheckUI.mountEvidenceDisclosure(result,document):{body:result.querySelector('.rent-check-summary')};
const studioNote=document.querySelector('#rentCheckStudioNote');
const nextStep=feedback.nextStep;
const nextHeading=feedback.nextHeading;
const nextBody=feedback.nextBody;
const nextPrimary=feedback.nextPrimary;
let acquisitionContext={};
let latestResultContext=null;
let comparablesExpanded=false;
const analyticsDistrictCodes=new Set(['11680','11440','11170','11200','11560','11620','11230','11410','11290','11215','11110','11140','11260','11305','11320','11350','11380','11470','11500','11530','11545','11590','11650','11710','11740']);
const analyticsPropertyTypes=new Set(['apartment','officetel','villa','detached']);
let toolViewTracked=false;

function safeTrack(eventName,params){try{if(!params||typeof window.gtag!=='function')return false;window.gtag('event',eventName,params);return true;}catch(_){return false;}}
function toolPage(){const path=String(location.pathname||'');return['/','/zh/','/tools/seoul-rent-check/','/zh/tools/seoul-rent-check/'].includes(path)?path:'';}
function sourcePage(){return String(acquisitionContext.sourcePage||'')||toolPage();}
function trackBase(mapped,data){const districtCode=String(area&&area.value||''),propertyType=String(mapped&&mapped.officialType||'');if(!analyticsDistrictCodes.has(districtCode)||!analyticsPropertyTypes.has(propertyType))return null;return{language,source_page:sourcePage(),tool_page:toolPage(),district_code:districtCode,property_type:propertyType,rating:data&&data.rating||'',confidence:data&&data.confidence||'',sufficient:data?data.rating!=='insufficient':undefined};}
function errorCategory(err){if(err&&err.name==='AbortError')return'request_aborted';if(err&&err.name==='TypeError')return'network';if(err&&err.name==='SyntaxError')return'invalid_response';return'request_failed';}
function emitToolView(){if(toolViewTracked)return;const context=trackBase(KHGRentCheckUI.mapRentCheckType(type.value),null);if(safeTrack('rent_check_tool_view',context))toolViewTracked=true;}
function emitResult(data,mapped,depositWon,rentWon,sqm){const detail={language,sourcePage:acquisitionContext.sourcePage||location.pathname,savedQuoteId:acquisitionContext.savedQuoteId||null,districtCode:area.value,propertyType:mapped.officialType,savedPropertyType:type.value,depositWon,monthlyRentWon:rentWon,areaSqm:sqm,rating:data.rating||'insufficient',confidence:data.confidence||null,askingValueWon:data.askingValueWon??null,medianValueWon:data.medianValueWon??null,differencePct:data.differencePct??null,comparableCount:Number(data.comparableCount||0),monthsUsed:Number(data.monthsUsed||12),dataThroughMonth:data.dataThroughMonth||null};window.dispatchEvent(new CustomEvent('khg:rent-check-result',{detail}));safeTrack('rent_check_result',trackBase(mapped,data));}
function applyExplorerPrefill(){if(!window.KHGRentCheckPrefill)return;const queryPrefill=KHGRentCheckPrefill.readRentCheckPrefill(location.search);let savedPrefill=null;try{savedPrefill=window.KHGSavedQuotes?window.KHGSavedQuotes.takeRecheckPrefill(window.sessionStorage):null;}catch(_){}acquisitionContext={...queryPrefill,...(savedPrefill||{})};const prefill=acquisitionContext;if(prefill.lawdCd&&[...area.options].some(option=>option.value===prefill.lawdCd)){area.value=prefill.lawdCd;const EventCtor=window.Event||(typeof Event==='function'?Event:null);if(EventCtor&&typeof area.dispatchEvent==='function')area.dispatchEvent(new EventCtor('change',{bubbles:true}));}if(prefill.type&&[...type.options].some(option=>option.value===prefill.type))type.value=prefill.type;const hasArea=Object.prototype.hasOwnProperty.call(prefill,'areaSqm');if(sizeController)sizeController.setPropertyType(type.value,{preserveValue:hasArea});if(Object.prototype.hasOwnProperty.call(prefill,'depositWon'))deposit.dataset.krwValue=String(Math.round(prefill.depositWon));if(Object.prototype.hasOwnProperty.call(prefill,'rentWon'))rent.dataset.krwValue=String(Math.round(prefill.rentWon));if(hasArea)sizeController?sizeController.setPrefilledSqm(prefill.areaSqm):areaSqm.value=String(prefill.areaSqm);}
function setStatus(text,state=''){status.textContent=text;status.className=`rent-check-status${state?` ${state}`:''}`;if(status.dataset)status.dataset.state=state||'idle';}
function updateStudio(){studioNote.hidden=type.value!=='studio';}
function ensureMarketPosition(distribution){let visual=distribution.querySelector('#rentCheckPriceVisual');if(!visual){visual=document.createElement('div');visual.id='rentCheckPriceVisual';visual.className='rent-check-market-position';visual.hidden=true;visual.innerHTML=`<div class="rent-check-market-chart"><span class="rent-check-market-marker"><b>${zh?'你的报价':'Your quote'}</b></span><div class="rent-check-market-track" aria-hidden="true"><span class="rent-check-market-zone is-below"></span><span class="rent-check-market-zone is-typical"></span><span class="rent-check-market-zone is-above"></span></div></div><div class="rent-check-market-axis"><span class="is-p25"><small>P25</small><strong data-market-p25></strong></span><span class="is-median"><small>Median</small><strong data-market-median></strong></span><span class="is-p75"><small>P75</small><strong data-market-p75></strong></span></div><p class="rent-check-market-caption"></p>`;distribution.appendChild(visual);}return{visual,marker:visual.querySelector('.rent-check-market-marker'),p25:visual.querySelector('[data-market-p25]'),median:visual.querySelector('[data-market-median]'),p75:visual.querySelector('[data-market-p75]'),caption:visual.querySelector('.rent-check-market-caption')};}
function ensureDistributionPanel(){let distribution=document.querySelector('#rentCheckDistribution');if(!distribution){const copy=KHGRentCheckUI.distributionCopy();distribution=document.createElement('section');distribution.id='rentCheckDistribution';distribution.className='rent-check-intelligence';distribution.hidden=true;distribution.innerHTML=`<div class="rent-check-evidence-head"><div><strong>${copy.title}</strong><span>${copy.subtitle}</span></div></div>`;evidenceDisclosure.body.appendChild(distribution);}return distribution;}
function renderDistribution(data){const distribution=ensureDistributionPanel();const model=KHGRentCheckUI.distributionModel(data);const{visual,marker,p25,median:medianAxis,p75,caption}=ensureMarketPosition(distribution);distribution.hidden=!model;visual.hidden=!model;if(!model)return;p25.innerHTML=moneyHtml(model.p25ValueWon);medianAxis.innerHTML=moneyHtml(model.medianValueWon);p75.innerHTML=moneyHtml(model.p75ValueWon);marker.style.left=`${model.quotePct}%`;visual.dataset.relation=model.relation;const percentile=KHGRentCheckUI.percentileSentence(data);const position=KHGRentCheckUI.marketPositionSummary(model);caption.innerHTML=model.relation==='within'?`<span>${escapeHtml(percentile)}</span><strong>${escapeHtml(position)}</strong>`:`<span>${escapeHtml(percentile)}</span><strong>${moneyHtml(model.gapWon)} ${escapeHtml(position)}</strong>`;visual.setAttribute('aria-label',caption.textContent);}
function renderEvidenceFacts(data){const facts=KHGRentCheckUI.evidenceFacts(data);meta.className='rent-check-evidence-facts';meta.innerHTML=`<span>${escapeHtml(facts.sampleLabel)}</span><span>${escapeHtml(facts.periodLabel)}</span>${facts.methodLabel?`<span>${escapeHtml(facts.methodLabel)}</span>`:''}<span>${escapeHtml(facts.sourceLabel)}</span>`;}
function updateComparablesDisclosure(total){const state=KHGRentCheckUI.comparableDisclosure(total,comparablesExpanded);body.classList.toggle('is-expanded',comparablesExpanded);comparablesToggle.hidden=!state.showToggle;comparablesToggle.textContent=state.label;comparablesToggle.setAttribute('aria-expanded',String(comparablesExpanded));}
function renderRows(items){const rows=Array.isArray(items)?items:[];comparablesExpanded=false;const labels=zh?['楼盘 / 建筑','面积','押金','月租','日期']:['Building','Size','Deposit','Monthly rent','Date'];body.innerHTML=rows.length?rows.map((item,index)=>`<tr${index>=3?' class="rent-check-mobile-extra"':''}><td data-label="${labels[0]}">${escapeHtml(item.building||'-')}</td><td data-label="${labels[1]}">${Number(item.areaSqm).toFixed(1)}㎡</td><td data-label="${labels[2]}">${moneyHtml(item.depositWon)}</td><td data-label="${labels[3]}">${moneyHtml(item.monthlyRentWon)}</td><td data-label="${labels[4]}">${KHGDate.formatDate(item.contractDate,locale)}</td></tr>`).join(''):`<tr class="empty-row"><td colspan="5">${zh?'暂时没有足够可靠的可比成交记录。':'No reliable comparable set is available.'}</td></tr>`;updateComparablesDisclosure(rows.length);}
function renderConfidence(data,mapped){const explanation=KHGRentCheckUI.confidenceExplanation(data,mapped.isStudioMapped);confidenceSummary.textContent=KHGRentCheckUI.confidenceQuestion(data);confidenceDetails.hidden=!explanation;confidenceExplanation.textContent=explanation;if(explanation)confidenceDetails.open=false;}
function setNextAction(anchor,action,exploreHref,marketHref){anchor.textContent=action.label;anchor.href=action.href==='explore'?exploreHref:action.href==='market'?(marketHref||exploreHref):action.href;anchor.dataset.actionId=action.id;}
function renderNextStep(data,mapped){const config=KHGRentCheckUI.resultNextStep(data.rating);const exploreHref=KHGRentCheckUI.explorerUrl(area.value,mapped.officialType,language);const marketHref=KHGRentCheckUI.marketPageUrl(area.value,mapped.officialType,language);nextHeading.textContent=config.heading;nextBody.textContent=config.body;setNextAction(nextPrimary,config.primary,exploreHref,marketHref);nextStep.hidden=false;latestResultContext={mapped,data};}
function trackNextAction(anchor){if(!latestResultContext)return;const context=trackBase(latestResultContext.mapped,latestResultContext.data);if(context)safeTrack('rent_check_next_action',{...context,action_id:String(anchor.dataset.actionId||'')});}
function renderResult(data,mapped){result.hidden=false;result.dataset.rating=data.rating||'insufficient';const verdictModel=KHGRentCheckUI.verdictPresentation(data);verdictFeedback.primary.dataset.rating=data.rating||'insufficient';verdictFeedback.icon.textContent=verdictModel.icon;verdictFeedback.label.textContent=verdictModel.label;verdictFeedback.difference.textContent=verdictModel.difference;verdictFeedback.comparison.textContent=verdictModel.comparison;verdictFeedback.annualized.textContent=verdictModel.annualized;verdictFeedback.annualized.hidden=!verdictModel.annualized;verdictFeedback.sample.textContent=verdictModel.sample;rating.textContent=KHGRentCheckUI.ratingLabel(data.rating,data.verdictBasis);rating.className=`rent-rating ${data.rating||'insufficient'}`;message.textContent=KHGRentCheckUI.resultSentence(data);asking.innerHTML=moneyHtml(data.askingValueWon);median.innerHTML=data.medianValueWon==null?'-':moneyHtml(data.medianValueWon);if(difference){difference.textContent=data.differencePct==null?'-':KHGRentCheckUI.formatDifference(data.differencePct);difference.parentElement.hidden=true;}if(data.confidence){confidence.hidden=false;confidence.textContent=KHGRentCheckUI.confidenceLabel(data.confidence);confidence.className=`confidence-pill ${data.confidence}`;}else confidence.hidden=true;const count=Number(data.comparableCount||0);renderEvidenceFacts(data);summary.hidden=true;renderConfidence(data,mapped);renderDistribution(data);renderRows(data.comparables||[]);renderNextStep(data,mapped);}

if(form)form.addEventListener('submit',async e=>{e.preventDefault();const validMoney=syncCurrencyInput(deposit)&&syncCurrencyInput(rent);if(!validMoney)return setStatus(zh?'请输入有效的非负押金和月租金额。':'Enter valid non-negative deposit and monthly rent amounts.','error');const depositWon=getInputWon(deposit),rentWon=getInputWon(rent),sqm=window.KHGRentSize?KHGRentSize.readSqm(areaSqm):Number(areaSqm.value);if(!Number.isFinite(sqm)||sqm<=0)return setStatus(zh?'请输入面积，或选择一个大致房型。':'Enter the size or choose a rough room size.','error');const mapped=KHGRentCheckUI.mapRentCheckType(type.value);updateStudio();setStatus(zh?'正在查找类似的官方成交记录…':'Finding similar official contracts…','loading');button.disabled=true;safeTrack('rent_check_start',trackBase(mapped,null));try{const q=new URLSearchParams({lawdCd:area.value,type:mapped.officialType,deposit:String(Math.round(depositWon)),rent:String(Math.round(rentWon)),area:String(sqm)});const r=await fetch(`/api/rent-check?${q}`);const data=await r.json();if(!r.ok)throw new Error(data.error||(zh?'租金比较失败。':'Rent comparison failed.'));renderResult(data,mapped);emitResult(data,mapped,depositWon,rentWon,sqm);setStatus('','idle');KHGRentCheckResultReveal.reveal(result,window);}catch(err){const context=trackBase(mapped,null);if(context)safeTrack('rent_check_error',{...context,error_category:errorCategory(err)});result.hidden=true;setStatus(KHGRentCheckUI.humanizeRentCheckError(err.message),'error');}finally{button.disabled=false;}});
if(type)type.addEventListener('change',updateStudio);
if(nextPrimary)nextPrimary.addEventListener('click',()=>trackNextAction(nextPrimary));
if(confidenceDetails)confidenceDetails.addEventListener('toggle',()=>{if(confidenceDetails.open&&latestResultContext){const context=trackBase(latestResultContext.mapped,latestResultContext.data);if(context)safeTrack('rent_check_confidence_open',context);}});
if(comparablesToggle)comparablesToggle.addEventListener('click',()=>{comparablesExpanded=!comparablesExpanded;updateComparablesDisclosure(body.querySelectorAll('tr:not(.empty-row)').length);if(comparablesExpanded&&latestResultContext){const context=trackBase(latestResultContext.mapped,latestResultContext.data);if(context)safeTrack('rent_check_comparables_expand',context);}});
applyExplorerPrefill();if(typeof window.addEventListener==='function')window.addEventListener('khg:analytics-ready',emitToolView);if(window.KHGAnalyticsReady===true)emitToolView();updateStudio();loadFx();
})();
