export type CollectionSource = {
  id: string; name: string; market: 'seoul' | 'singapore' | 'dubai';
  category: 'building' | 'cost' | 'policy' | 'asking-price';
  url: string; intervalDays: number; mode: 'page-monitor' | 'building-api' | 'blocked'; limitation: string;
};
// Fixed destinations only. Provider credentials and arbitrary submitted URLs never enter this runner.
export const COLLECTION_SOURCES: readonly CollectionSource[] = [
  { id: 'sg-hdb-buildings', name: 'HDB Property Information', market: 'singapore', category: 'building', url: 'https://data.gov.sg/datasets/d_17f5382f26140b1fdae0ba2ef6239d2f/view', intervalDays: 7, mode: 'building-api', limitation: 'Official building records matched by unique block/street; normalized changes remain pending review. No coordinates are inferred.' },
  { id: 'sg-iras-bsd', name: 'IRAS Buyer Stamp Duty', market: 'singapore', category: 'policy', url: "https://www.iras.gov.sg/taxes/stamp-duty/for-property/buying-or-acquiring-property/buyer's-stamp-duty-(bsd)", intervalDays: 7, mode: 'page-monitor', limitation: 'Internal change monitoring; rates and effective conditions require human review before calculation use.' },
  { id: 'kr-seoul-broker-fees', name: 'Seoul brokerage fee caps', market: 'seoul', category: 'policy', url: 'https://land.seoul.go.kr/land/broker/brokerageCommission.do', intervalDays: 7, mode: 'page-monitor', limitation: 'Negotiable legal caps; VAT and contract conditions require review. Page monitoring does not approve a calculation rule.' },
  { id: 'sg-amktc-cost', name: 'Ang Mo Kio Town Council service charges', market: 'singapore', category: 'cost', url: 'https://www.amktc.org.sg/service-and-conservancy-charges-scc/index.html', intervalDays: 30, mode: 'page-monitor', limitation: 'Council-specific HDB charges, normal/subsidised eligibility and effective-date sections require review; not applicable to all Singapore buildings.' },
  { id: 'ae-dld-sale-fees', name: 'Dubai sale registration fees', market: 'dubai', category: 'policy', url: 'https://dubailand.gov.ae/en/eservices/property-sale-registration/', intervalDays: 7, mode: 'page-monitor', limitation: 'Internal monitoring only; fee conditions and commercial reuse require review before publication.' },
  { id: 'ae-dld-service-index', name: 'Dubai service charge index documentation', market: 'dubai', category: 'cost', url: 'https://dubailand.gov.ae/en/eservices/service-charge-index-overview/', intervalDays: 30, mode: 'page-monitor', limitation: 'Monitors service documentation, not project charge amounts; project/year queries and reuse rights remain unverified.' },
  { id: 'kr-kapt-cost', name: 'K-apt management costs', market: 'seoul', category: 'cost', url: 'https://www.k-apt.go.kr/', intervalDays: 30, mode: 'blocked', limitation: 'Official common-management API catalog confirms free unrestricted data, V3 endpoint verified; runtime subscription, unit interpretation and complex identifiers need verification before collection.' },
  { id: 'sg-onemap-building', name: 'OneMap building addresses', market: 'singapore', category: 'building', url: 'https://www.onemap.gov.sg/apidocs/', intervalDays: 7, mode: 'blocked', limitation: 'Authenticated token and permitted storage scope required; no successful collection asserted.' },
  { id: 'ae-dld-cost', name: 'Dubai Land Department service charges', market: 'dubai', category: 'cost', url: 'https://dubailand.gov.ae/', intervalDays: 30, mode: 'blocked', limitation: 'Project-level retrieval and commercial reuse must be verified before ingestion.' },
  { id: 'licensed-listings', name: 'Licensed asking prices', market: 'singapore', category: 'asking-price', url: 'https://www.signedprice.com/', intervalDays: 1, mode: 'blocked', limitation: 'No licensed listing feed configured. Asking prices remain separate from recorded transactions.' },
];
