'use client';
import type {ScenarioCostOption} from '../../lib/evidence-pool/costs';
import { shortlistHref as marketHref } from '../global-shortlist/copy';
import { PassportLink as Link } from '../passport/passport-journey';
import { useState } from 'react';
import { PropertyScenarioCalculator } from '../market-ui/property-scenario';
import type {PropertyScenarioContext,ToolMarket,ScenarioCurrency} from '../../lib/tools/property-scenario-context';
import styles from './tools.module.css';
import type {ScenarioRentOption} from '../../lib/tools/scenario-rent-options.server';
const currencies={'kr-seoul':'KRW','sg-singapore':'SGD','ae-dubai':'AED','jp-tokyo':'JPY'} as const;
export function PropertyScenarioWorkspace({context,locale,rentOptions=[],costOptions=[],costState='ready'}:Readonly<{costOptions?:ScenarioCostOption[];costState?:'ready'|'unavailable';rentOptions?:ScenarioRentOption[];context:PropertyScenarioContext;locale:'en'|'ko'|'zh-CN'}>) {
 const [active,setActive]=useState(context); const ko=locale==='ko', zh=locale==='zh-CN';
 const guideMarket=active.market.split('-')[1];
 return <><div className={styles.context}><label>{ko?'도시 · 통화': (zh ? "城市 · 货币" : 'Market · currency')}<select value={active.market} onChange={event=>{const market=event.target.value as ToolMarket;setActive({...context,market,currency:currencies[market] as ScenarioCurrency,annualRent:null,price:null,propertyName:null,entity:null,returnTo:null,areaSqm:null,areaBand:undefined,housing:null,transaction:null}); const url=new URL(location.href);url.search='';url.searchParams.set('market',market);url.searchParams.set('currency',currencies[market]);if(context.passportHref) url.searchParams.set('passport',context.passportHref);history.replaceState(null,'',url);}}><option value="kr-seoul">{ko?'서울 · KRW': (zh ? "首尔 · KRW" : 'Seoul · KRW')}</option><option value="sg-singapore">{ko?'싱가포르 · SGD': (zh ? "新加坡 · SGD" : 'Singapore · SGD')}</option><option value="ae-dubai">{ko?'두바이 · AED': (zh ? "迪拜 · AED" : 'Dubai · AED')}</option><option value="jp-tokyo">{ko?'도쿄 · JPY': (zh ? "东京 · JPY" : 'Tokyo · JPY')}</option></select></label>{active.propertyName?<p>{active.propertyName}{active.areaSqm?` · ${active.areaSqm} m²`:''}</p>:null}{active.returnTo?<Link href={marketHref(locale, active.returnTo)}>{ko?'거래 내역으로 돌아가기': (zh ? "返回交易资料" : 'Return to property evidence')}</Link>:null}{active.passportHref?<Link href={marketHref(locale, active.passportHref)}>{ko?'내 예산 비교로 돌아가기': (zh ? "返回跨城市预算" : 'Return to my Passport budget')}</Link>:null}</div><p>{ko?"도시를 바꾸면 통화가 달라져 입력값이 초기화됩니다.":zh?"切换城市会因货币改变而重置输入。":"Changing cities resets the inputs because the currency changes."}</p><PropertyScenarioCalculator costOptions={active.market===context.market && active.propertyName===context.propertyName ? costOptions : []} costState={costState} key={`${active.market}-${active.entity}`} price={active.price} annualRent={active.annualRent} rentOptions={active.market === 'ae-dubai' ? rentOptions : []} areaSqm={active.areaSqm} areaBand={active.areaBand} housingType={active.housing} currency={active.currency} locale={locale} analytics={{market:active.market,surface:'standalone-tool'}}/><nav className={styles.links} aria-label={ko?'관련 자료': (zh ? "相关资料" : 'Related evidence')}><Link href={marketHref(locale, active.market==='kr-seoul'?'/kr/seoul/explore/':active.market==='sg-singapore'?'/sg/singapore/explore/':active.market==='jp-tokyo'?'/jp/tokyo/explore/':'/ae/dubai/explore/')}>{ko?'실거래가 보기': (zh ? "探索" : 'Explore')}</Link><Link href={`${ko?'/ko':zh?'/zh-cn':''}/tools/`}>{ko?'모든 도구': (zh ? "所有工具" : 'All tools')}</Link><Link href={`${ko?"/ko":zh?"/zh-cn":""}/guides/?market=${guideMarket}`}>{ko?"매수·임대 가이드":zh?"买房与租房指南":"Buying & renting guides"}</Link></nav></>;
}
