'use client';
import Link from 'next/link';
import { useState } from 'react';
import { PropertyScenarioCalculator } from '../market-ui/property-scenario';
import type {PropertyScenarioContext,ToolMarket,ScenarioCurrency} from '../../lib/tools/property-scenario-context';
import styles from './tools.module.css';
import type {ScenarioRentOption} from '../../lib/tools/scenario-rent-options.server';
const currencies={'kr-seoul':'KRW','sg-singapore':'SGD','ae-dubai':'AED'} as const;
export function PropertyScenarioWorkspace({context,locale,rentOptions=[]}:Readonly<{rentOptions?:ScenarioRentOption[];context:PropertyScenarioContext;locale:'en'|'ko'}>) {
 const [active,setActive]=useState(context); const ko=locale==='ko'; const [rentId,setRentId]=useState(''); const rent=rentOptions.find(option=>option.id===rentId);
 return <><div className={styles.context}><label>{ko?'시장 · 통화':'Market · currency'}<select value={active.market} onChange={event=>{const market=event.target.value as ToolMarket;setRentId('');setActive({...context,market,currency:currencies[market] as ScenarioCurrency,annualRent:null,price:null,propertyName:null,entity:null,returnTo:null,areaSqm:null,housing:null,transaction:null}); const url=new URL(location.href);url.search='';url.searchParams.set('market',market);url.searchParams.set('currency',currencies[market]);if(context.passportHref) url.searchParams.set('passport',context.passportHref);history.replaceState(null,'',url);}}><option value="kr-seoul">Seoul · KRW</option><option value="sg-singapore">Singapore · SGD</option><option value="ae-dubai">Dubai · AED</option></select></label>{active.propertyName?<p>{active.propertyName}{active.areaSqm?` · ${active.areaSqm} m²`:''}</p>:null}{active.returnTo?<Link href={active.returnTo}>{ko?'원래 거래 근거로 돌아가기':'Return to property evidence'}</Link>:null}{active.passportHref?<Link href={active.passportHref}>{ko?'내 Passport 예산으로 돌아가기':'Return to my Passport budget'}</Link>:null}</div>{active.market==='ae-dubai' && rentOptions.length>0 && <label className={styles.context}>{ko?'임대료 시작값 · 지역과 주택 유형':'Rent starting point · area and home type'}<select value={rentId} onChange={event=>setRentId(event.target.value)}><option value="">{ko?'직접 입력':'Enter my own rent'}</option>{rentOptions.map(option=><option key={option.id} value={option.id}>{option.name} · {option.housing} · AED {option.annualRent.toLocaleString('en')}/year</option>)}</select></label>}<PropertyScenarioCalculator key={`${active.market}-${active.entity}-${rentId}`} price={active.price} annualRent={rent?.annualRent ?? active.annualRent} areaSqm={active.areaSqm} housingType={active.housing} rentSource={rent ? `${rent.name} · ${rent.housing} · ${ko?'지역 신규 임대계약 중앙값':'area median of new rent contracts'} · n=${rent.count} · ${rent.period} · DLD` : undefined} currency={active.currency} locale={locale} analytics={{market:active.market,surface:'standalone-tool'}}/><nav className={styles.links} aria-label={ko?'관련 자료':'Related evidence'}><Link href={active.market==='kr-seoul'?`${ko?'/ko':''}/kr/seoul/explore/`:active.market==='sg-singapore'?'/sg/singapore/explore/':'/ae/dubai/explore/'}>Explore</Link><Link href={`${ko?'/ko':''}/tools/`}>{ko?'모든 도구':'All tools'}</Link><Link href="/guides/">Guides</Link></nav></>;
}
