import Link from 'next/link';
import { ResearchPageHeading } from '../market-ui/research-page-heading';
import { DUBAI_ANNUAL_TRANSACTIONS, DUBAI_RESEARCH_DATE, DUBAI_SOURCES } from '../../lib/dubai/research';
import styles from './dubai-research.module.css';

export function DubaiOverview() {
  return <main className={styles.main}>
    <ResearchPageHeading title="Dubai" description="Read the market, locate an area and build a purchase budget. Start with official releases, then verify the exact project and property before comparing offers." actions={<><Link href="/ae/dubai/explore/">Explore areas →</Link><Link href="/ae/dubai/guide/">Buying research guide →</Link><Link href="/news/?market=dubai">News →</Link></>} />
    <section className={styles.section} aria-labelledby="dubai-annual-heading"><h2 id="dubai-annual-heading">Annual transaction activity</h2><p>The government reported AED 917 billion in real estate transactions for 2025, compared with AED 761 billion for 2024. These totals cover the wider property market and transaction categories; they are not residential sale-price indices.</p><figure className={styles.chart} aria-label="Dubai annual real estate transaction value in AED billions"><div><span>2024</span><i className={styles.bar} style={{width: `${761 / 1000 * 100}%`}} /><strong>AED 761B</strong></div><div><span>2025</span><i className={styles.bar} style={{width: `${917 / 1000 * 100}%`}} /><strong>AED 917B</strong></div><figcaption>Zero-based scale: AED 0–1,000 billion. Sources: {DUBAI_ANNUAL_TRANSACTIONS.map((row, index) => <span key={row.year}>{index > 0 ? ' · ' : ''}<a href={row.source}>{row.year} government release</a> ({row.published})</span>)}.</figcaption></figure></section>
    <section className={styles.section} aria-labelledby="dubai-quarter-heading"><h2 id="dubai-quarter-heading">Q1 2026 · a separate reporting period</h2><dl className={styles.metrics}><div><dt>Total transaction value</dt><dd>AED 252B</dd></div><div><dt>Real estate transactions</dt><dd>60,303</dd></div><div><dt>Value change · year on year</dt><dd>+31%</dd></div></dl><p>DLD’s release dated 9 April 2026 compares Q1 with the same quarter of 2025. The quarterly result is kept separate from the full-year chart. It does not establish a current price for an individual home. <a href={DUBAI_SOURCES.quarter2026}>Read the DLD release</a>.</p></section>
    <section className={styles.section} aria-labelledby="dubai-checks-heading"><h2 id="dubai-checks-heading">Move from the city to the exact property</h2><p>Use the area directory to frame your search. For a shortlist, record the project number, unit identity, completion status and recurring costs. The guide brings those checks and an AED cost calculator together.</p><nav className={styles.actions} aria-label="Official Dubai tools"><a href={DUBAI_SOURCES.projects}>Project status</a><a href={DUBAI_SOURCES.charges}>Service charges</a><a href={DUBAI_SOURCES.services}>Title, broker and developer checks</a><a href={DUBAI_SOURCES.data}>DLD public data</a></nav><p>Coverage: selected area context and dated aggregate releases. SignedPrice does not currently publish Dubai property-level transactions, rental estimates or available listings. Sources checked {DUBAI_RESEARCH_DATE}.</p></section>
  </main>;
}
